Repository vaadin/docs, pull requests merged in 2022-06, with the labels that each got.

#1419 feat: Add documentation for UI Unit Testing with Spring
  articles/tools/testbench/ui-unit-testing/spring-tests.asciidoc
Labels: Language checked

#1352 feat: Add ListInsertOperation documentation
  articles/ce/advanced/collaboration-list.asciidoc
  src/main/java/com/vaadin/demo/ce/CollaborationListExample.java
Labels: Language checked

#1438 Update DSP instructions to use new branch
  articles/tools/dspublisher/start.asciidoc
  articles/tools/dspublisher/updating.asciidoc
Labels: Language not checked

#1432 docs: Review package scan instructions after refactoring
  articles/tools/testbench/ui-unit-testing/getting-started.asciidoc
Labels: Language checked

#1447 Simplify route-parameters instructions
  articles/routing/additional-guides/index.adoc
  articles/routing/additional-guides/query-parameters.asciidoc
  articles/routing/additional-guides/route-templates.asciidoc
  articles/routing/dynamic.asciidoc
  articles/routing/exceptions.asciidoc
  articles/routing/layout.asciidoc
  articles/routing/lifecycle.asciidoc
  articles/routing/navigation.asciidoc
  articles/routing/page-titles.asciidoc
  articles/routing/registered-routes.asciidoc
  articles/routing/route-parameters.asciidoc
  articles/routing/route.adoc
  articles/routing/url-generation.asciidoc
  articles/routing/url-parameters.asciidoc
Labels: Language not checked

#1463 Adding @RouteAlias documentation
  articles/routing/route.adoc
Labels: Language not checked

#1469 Adding special exception for @Route derived route
  articles/routing/route.adoc
Labels: Language not checked

#1470 Clarifying empty wildcard parameter default value
  articles/routing/route-parameters.asciidoc
Labels: Language checked

#1462 Emphasize usage of Chrome WebDriverManager in e2e Test Tutorial
  articles/tutorial/e2e-testing-with-testbench.adoc
Labels: Language checked

#1468 Adding link to java.util.regex.Pattern class
  articles/routing/additional-guides/route-templates.asciidoc
Labels: Language checked

#1488 refactor: update docs after naming changes in UI Unit Testing
  articles/tools/testbench/ui-unit-testing/getting-started.asciidoc
  articles/tools/testbench/ui-unit-testing/searching-components.asciidoc
  articles/tools/testbench/ui-unit-testing/spring-tests.asciidoc
Labels: Language not checked

#1480 Documenting the usage of return type for programmatic navigation
  articles/routing/index.asciidoc
  articles/routing/navigation.asciidoc
  articles/routing/route-parameters.asciidoc
  articles/routing/updating-url-parameters.asciidoc
Labels: Language not checked

#1489 Move Icons under /components
  articles/application/resources.asciidoc
  articles/components/ds-resources/foundation/icons/index.asciidoc
  articles/components/ds-resources/foundation/icons/vaadin.asciidoc
  articles/components/ds-resources/foundation/size-space.asciidoc
  articles/components/icons/index.asciidoc
  articles/components/index.asciidoc
  frontend/demo/foundation/icons-preview.ts
  frontend/demo/foundation/lumo-icons.ts
  frontend/demo/foundation/vaadin-icons.ts
Labels: Language not checked

#1464 chore: Added a note with link for testing with spring
  articles/tools/testbench/ui-unit-testing/getting-started.asciidoc
Labels: Language checked

#1501 Advice to upgrade maven-failsafe-plugin instead of jaxb
  articles/upgrading/essential-steps/instructions/_common.adoc
Labels: flow, Language not checked

#1341 refactor: update npm scripts to use the new dsp
  articles/tools/dspublisher/devmode.asciidoc
  articles/tools/dspublisher/start.asciidoc
  articles/tools/dspublisher/troubleshooting.asciidoc
  dspublisher/docker-compose.build.yml
  dspublisher/docker-compose.develop.yml
  dspublisher/docker-compose.rmtarget.yml
  dspublisher/dspublisher-scripts.js
  package.json
Labels: Language checked

#1492 Improving routing exceptions doc
  articles/routing/exceptions.asciidoc
Labels: Language checked

#1497 Hilla: update the boolean binding example for `<vaadin-select>`
  articles/data-binding/vaadin-components.asciidoc
Labels: hilla, Language checked

#1490 Improving URL Generation doc
  articles/routing/retrieving-routes.asciidoc
Labels: Language checked

#1484 Improve router layout guide
  articles/routing/layout.asciidoc
Labels: Language checked

#1499 Remove mention of VaadinServletConfiguration
  articles/advanced/application-lifecycle.asciidoc
  articles/configuration/properties.asciidoc
  articles/integrations/spring/spring-mvc.asciidoc
Labels: flow, Language checked

#1503 Improving Page Title doc
  articles/routing/page-titles.asciidoc
Labels: Language checked

#1519 Add note for HasUrlParameter
  articles/routing/route-parameters.asciidoc
Labels: Language checked
