Repository vaadin/docs, pull requests merged in 2022-09, with the labels that each got.

#1673 Add note about not to include non-legacy CSS in legacy theme
  articles/tools/mpr/configuration/legacy-theme.asciidoc
Labels: Language not checked

#1682 Updated Map docs for 23.2
  articles/components/map/index.asciidoc
Labels: Language not checked

#1683 feat: add MenuBar Alignment section
  articles/components/menu-bar/index.asciidoc
  frontend/demo/component/menubar/menu-bar-right-aligned.ts
  src/main/java/com/vaadin/demo/component/menubar/MenuBarRightAligned.java
Labels: Language not checked

#1684 feat: add Preventing Invalid Input section to TextField
  articles/components/text-field/index.asciidoc
  frontend/demo/component/textfield/text-field-allowed-char-pattern.ts
  src/main/java/com/vaadin/demo/component/textfield/TextFieldAllowedCharPattern.java
Labels: Language not checked

#1653 docs: ConfigurerAdapter to component-based security configuration
  articles/security/enabling-security.adoc
Labels: Language checked

#1635 make vite as the default frontend build tool
  .github/styles/Vocab/Docs/accept.txt
  articles/advanced/loading-resources.asciidoc
  articles/advanced/modifying-the-bootstrap-page.asciidoc
  articles/configuration/live-reload/index.asciidoc
  articles/configuration/maven.asciidoc
  articles/configuration/node-js.asciidoc
  articles/configuration/properties.asciidoc
  articles/configuration/source-control.adoc
  articles/guide/start/gradle.asciidoc
  articles/integrations/osgi/index.asciidoc
  articles/integrations/portlet/creating-vaadin-portlets.asciidoc
  articles/integrations/spring/spring-boot.asciidoc
  articles/production/index.asciidoc
  articles/production/production-build.adoc
  articles/production/troubleshooting.asciidoc
  articles/styling/custom-theme/creating-custom-theme.adoc
  articles/tutorial/project-setup.adoc
Labels: Language checked

#1688 Updated V14 upgrade guide for V23.2
  articles/upgrading/essential-steps/instructions/_typescript.adoc
Labels: Language not checked

#1701 add custom instrumentation doc
  articles/tools/observability/advanced/custom-instrumentation.asciidoc
Labels: Language not checked

#1704 docs: improve observability overview
  articles/tools/observability/overview.asciidoc
Labels: Language not checked

#1705 feat: start Integrations main page
  articles/tools/observability/integrations/integrations.asciidoc
Labels: Language not checked

#1713 feat: add long running/threaded span example
  articles/tools/observability/advanced/custom-instrumentation.asciidoc
Labels: Language not checked

#1716 refactor: Testing section
  .github/styles/Vocab/Docs/accept.txt
  articles/api.adoc
  articles/testing/browser-based/advanced-testing-concepts.asciidoc
  articles/testing/browser-based/bdd.asciidoc
  articles/testing/browser-based/ci-server.asciidoc
  articles/testing/browser-based/creating-tests.asciidoc
  articles/testing/browser-based/demo-external.asciidoc
  articles/testing/browser-based/getting-started.asciidoc
  articles/testing/browser-based/index.asciidoc
  articles/testing/browser-based/installing-webdrivers.asciidoc
  articles/testing/browser-based/javadoc-external.asciidoc
  articles/testing/browser-based/low-level-element-interactions.asciidoc
  articles/testing/browser-based/maintainable-tests-using-page-objects.asciidoc
  articles/testing/browser-based/making-tests-reliable.asciidoc
  articles/testing/browser-based/migration.asciidoc
  articles/testing/browser-based/own-grid.asciidoc
  articles/testing/browser-based/running-test-on-multiple-browsers.asciidoc
  articles/testing/browser-based/running-with-maven.asciidoc
  articles/testing/browser-based/screenshots.asciidoc
  articles/testing/browser-based/selenium-testing.adoc
  articles/testing/browserless/getting-started.asciidoc
  articles/testing/browserless/index.asciidoc
  articles/testing/browserless/searching-components.asciidoc
  articles/testing/browserless/spring-tests.asciidoc
  articles/testing/browserless/ui-unit-testing-screenshot.asciidoc
  articles/testing/end-to-end/advanced-concepts.adoc
  articles/testing/end-to-end/bdd.adoc
  articles/testing/end-to-end/ci-server.adoc
  articles/testing/end-to-end/creating-tests.adoc
  articles/testing/end-to-end/getting-started.adoc
  articles/testing/end-to-end/img/screenshot-html-output.png
  articles/testing/end-to-end/img/screenshot-reference.png
  articles/testing/end-to-end/index.adoc
  articles/testing/end-to-end/installing-webdrivers.adoc
  articles/testing/end-to-end/low-level-api.adoc
  articles/testing/end-to-end/maven.adoc
  articles/testing/end-to-end/multiple-browsers.adoc
  articles/testing/end-to-end/page-objects.adoc
  articles/testing/end-to-end/reliable-tests.adoc
  articles/testing/end-to-end/screenshots.adoc
  articles/testing/end-to-end/test-grid.adoc
  articles/testing/img/screenshot-error.png
  articles/testing/index.adoc
  articles/testing/index.asciidoc
  articles/testing/selenium.adoc
  articles/testing/ui-unit/component-query.adoc
  articles/testing/ui-unit/getting-started.adoc
  articles/testing/ui-unit/index.adoc
  articles/testing/ui-unit/snapshots.adoc
  articles/testing/ui-unit/spring.adoc
Labels: Language not checked

#1696 Reactive Endpoints in Hilla
  articles/advanced/reactive-endpoints.asciidoc
  frontend/demo/fusion/reactive/reactive-view.ts
  package-lock.json
  src/main/java/com/vaadin/demo/fusion/reactive/ReactiveEndpoint.java
Labels: hilla, Language checked

#1734 chore: added documentation for CdiComponent annotation
  articles/integrations/cdi/contexts.asciidoc
Labels: Language checked

#1772 docs: add Tooltip documentation and examples
  articles/components/accordion/index.asciidoc
  articles/components/button/index.asciidoc
  articles/components/crud/index.asciidoc
  articles/components/details/index.asciidoc
  articles/components/grid/index.asciidoc
  articles/components/input-fields/index.asciidoc
  articles/components/menu-bar/index.asciidoc
  articles/components/tooltip/index.asciidoc
  frontend/demo/component/grid/grid-tooltip-generator.ts
  frontend/demo/component/menubar/menu-bar-tooltip.ts
  frontend/demo/component/tooltip/tooltip-basic.ts
  frontend/demo/component/tooltip/tooltip-html-element.ts
  frontend/demo/component/tooltip/tooltip-manual.ts
  frontend/demo/component/tooltip/tooltip-positioning.ts
  frontend/themes/docs/components/vaadin-app-layout.css
  src/main/java/com/vaadin/demo/component/grid/GridTooltipGenerator.java
  src/main/java/com/vaadin/demo/component/menubar/MenuBarTooltip.java
  src/main/java/com/vaadin/demo/component/tooltip/TooltipBasic.java
  src/main/java/com/vaadin/demo/component/tooltip/TooltipHtmlElement.java
  src/main/java/com/vaadin/demo/component/tooltip/TooltipManual.java
  src/main/java/com/vaadin/demo/component/tooltip/TooltipPositioning.java
Labels: Language not checked

#1773 docs: Add TabSheet documentation and examples
  articles/components/tabs/index.asciidoc
  frontend/demo/component/tabs/tabsheet-basic.ts
  frontend/demo/component/tabs/tabsheet-lazy-initialization.ts
  frontend/demo/component/tabs/tabsheet-prefix-suffix.ts
  src/main/java/com/vaadin/demo/component/tabs/TabSheetBasic.java
  src/main/java/com/vaadin/demo/component/tabs/TabSheetLazyInitialization.java
  src/main/java/com/vaadin/demo/component/tabs/TabSheetPrefixSuffix.java
Labels: Language not checked

#1777 docs: tooltip improvements based on DX tests
  articles/components/tooltip/index.asciidoc
  src/main/java/com/vaadin/demo/component/grid/GridTooltipGenerator.java
Labels: Language not checked
