Repository vaadin/docs, pull requests merged in 2022-08, with the labels that each got.

#1551 Update Google Cloud deployment guide
  articles/production/cloud-providers/google/index.adoc
Labels: Language not checked

#1585 fix: add a note on template format
  articles/create-ui/templates/components.asciidoc
  articles/create-ui/templates/polymer/polymer-template-basic.asciidoc
Labels: Language checked

#1583 chore: update links to maven.org
  articles/integrations/portlet/creating-vaadin-portlets.asciidoc
Labels: Language checked

#1576 Remove wrong usage of @Push annotation
  articles/advanced/server-push.asciidoc
Labels: Language checked

#1578 Remove outdated mention of Vaadin Servlet customization
  articles/advanced/application-lifecycle.asciidoc
Labels: Language checked

#1589 fix: remove `com.vaadin.fusion` references and manually pick some updates from `latest`
  .github/auto-label.json
  .github/styles/Vaadin/ProductName.yml
  .github/styles/Vaadin/SourceCode.yml
  .github/styles/Vocab/Docs/accept.txt
  .gitignore
  .vale.ini
  articles/advanced/client-middleware.asciidoc
  articles/advanced/connection-indicator.asciidoc
  articles/advanced/typescript-client.asciidoc
  articles/application/error-handling.asciidoc
  frontend/demo/fusion/application/accessing-backend/ts-info/index.ts
  frontend/demo/fusion/authentication/auth.ts
  frontend/demo/fusion/authentication/handle-session-expiration/connect-client.ts
  frontend/demo/fusion/authentication/handle-session-expiration/login-overlay.ts
  frontend/demo/fusion/authentication/login-view.ts
  frontend/demo/fusion/errorhandling/catch-error.ts
  frontend/demo/fusion/errorhandling/catch-invalid-args.ts
  frontend/demo/fusion/forms/contact-form.ts
  frontend/demo/fusion/forms/field-strategy/my-binder.ts
  frontend/demo/fusion/forms/field-strategy/my-form.ts
  frontend/demo/fusion/forms/field-strategy/my-text-field-strategy.ts
  frontend/demo/fusion/lit-basics/data-binding.ts
  frontend/demo/pwa/offline/ts-view-with-endpoint.ts
  frontend/web-component.html
  package.json
  pom.xml
  src/main/java/com/vaadin/demo/DashboardEndpoint.java
  src/main/java/com/vaadin/demo/fusion/accessingbackend/CounterEndpoint.java
  src/main/java/com/vaadin/demo/fusion/accessingbackend/CountryEndpoint.java
  src/main/java/com/vaadin/demo/fusion/errorhandling/DateEndpoint.java
  src/main/java/com/vaadin/demo/fusion/forms/ContactEndpoint.java
  src/main/java/com/vaadin/demo/fusion/forms/fieldstrategy/SamplePersonEndpoint.java
  src/main/java/com/vaadin/demo/fusion/security/authentication/UserInfoEndpoint.java
  src/main/java/com/vaadin/demo/pwa/offline/DataEndpoint.java
  tsconfig.json
  versions.json
  webpack.dspublisher.js
Labels: hilla

#1561 docs: map coordinate systems
  articles/components/map/index.asciidoc
  src/main/java/com/vaadin/demo/component/map/MapEvents.java
  src/main/java/com/vaadin/demo/component/map/MapMarkers.java
  src/main/java/com/vaadin/demo/component/map/MapViewport.java
Labels: Language checked

#1514 hilla: add an article to explain how to cancel endpoint requests
  articles/advanced/cancelling-endpoint-requests.asciidoc
  articles/application/error-handling.asciidoc
Labels: hilla, Language checked

#1580 Fix passing data via Route Parameters example
  articles/routing/navigation.asciidoc
Labels: Language checked

#1553 Add instructions for handling long-running tasks
  articles/advanced/images/vaadin-progress-bar-no-cancel.gif
  articles/advanced/images/vaadin-progress-bar-with-cancel.gif
  articles/advanced/long-running-tasks.adoc
Labels: Language checked

#1592 Update navigation.asciidoc
  articles/routing/navigation.asciidoc
Labels: Language checked

#1593 English-language updates wrt PR #1538
  articles/production/docker.adoc
Labels: Language not checked

#1594 Fix title of "Creating UI" chapter
  articles/create-ui/index.asciidoc
Labels: Language not checked

#1601 English-language updates wrt PR #1551
  articles/production/cloud-providers/google/index.adoc
Labels: Language not checked

#1588 docs: added note about new RouterLink constructors (#1587)
  articles/routing/navigation.asciidoc
Labels: Language checked

#1605 docs: mention combobox constructor changes in upgrade guide
  articles/upgrading/essential-steps/instructions/_common.adoc
Labels: Language not checked

#1609 docs: revert of removed fragment
  articles/routing/navigation.asciidoc
Labels: Language not checked

#1611 chore: remove commercial banner for ConfirmDialog
  articles/components/confirm-dialog/index.asciidoc
Labels: Language not checked

#1610 Update TestBench "Getting Started" guide title
  articles/testing/getting-started.asciidoc
Labels: Language checked

#1618 Remove reference to old vaadin.com/components
  articles/application/ui.asciidoc
  articles/create-ui/web-components/introduction-to-webcomponents.asciidoc
  articles/tools/designer/using-designer/layout.asciidoc
  articles/tutorial/creating-a-component.adoc
  articles/tutorial/overview.adoc
Labels: Language checked

#1614 Add since tag to UI Unit Testing articles
  articles/testing/ui-unit-testing/getting-started.asciidoc
  articles/testing/ui-unit-testing/index.asciidoc
  articles/testing/ui-unit-testing/searching-components.asciidoc
  articles/testing/ui-unit-testing/spring-tests.asciidoc
  articles/testing/ui-unit-testing/ui-unit-testing-screenshot.asciidoc
Labels: Language checked

#1537 Create Selenium guide
  articles/testing/selenium-testing.adoc
Labels: Language not checked

#1625 chore: add links to charts API and sources
  articles/components/charts/index.asciidoc
Labels: Language not checked

#1627 Add note about role of items' identities in data providers
  articles/binding-data/_items-identities.adoc
  articles/binding-data/data-provider.asciidoc
  articles/components/grid/flow.asciidoc
Labels: Language checked

#1562 Add guide on storing sensitive data
  articles/integrations/databases/_shared.adoc
  articles/integrations/databases/mariadb.adoc
  articles/integrations/databases/mysql.adoc
  articles/integrations/databases/postgresql.adoc
  articles/security/advanced-topics/external-configuration.adoc
  articles/security/advanced-topics/images/windows_env.png
Labels: Language not checked

#1604 Fix typos and clarifying lazy data binding
  articles/binding-data/data-provider.asciidoc
Labels: Language not checked

#1634 Clarify heartbeat effectiveness with the last UI
  articles/advanced/application-lifecycle.asciidoc
Labels: Language checked

#1658 docs: fix typos detected by cspell
  articles/binding-data/data-provider.asciidoc
  articles/components/charts/configuration.asciidoc
  articles/create-ui/templates/and-binder.asciidoc
  articles/integrations/quarkus.asciidoc
Labels: Language not checked

#1612 feat: add iconset generator
  articles/components/icons/index.asciidoc
  frontend/demo/component/icons/iconset-generator.ts
Labels: Language checked

#1607 Clarify how POJOs are instantiated with CDI
  articles/integrations/cdi/instantiated-beans.asciidoc
Labels: flow, Language checked

#1656 docs: fix applyTheme usage example
  articles/tools/dspublisher/ui-examples.asciidoc
Labels: Language checked
