Repository vaadin/docs, pull requests merged in 2022-03, with the labels that each got.

#1086 docs: add theme variants section for map component
  .github/styles/Vocab/Docs/accept.txt
  articles/ds/components/map/index.asciidoc
  frontend/demo/component/map/map-theme-borderless.ts
  src/main/java/com/vaadin/demo/component/map/MapThemeBorderless.java
Labels: AsciiDoc OK

#1132 Remove mentions of start.vaadin.com
  articles/flow/guide/start/images/newproject-flowchart-hi.png
  articles/flow/guide/start/images/newproject-flowchart.svg
  articles/flow/guide/start/images/project-customizing-01.png
  articles/flow/guide/start/index.asciidoc
  articles/flow/guide/start/project-wizard.asciidoc
Labels: AsciiDoc OK

#1105 Remove references to server side routing
  articles/routing/defining.asciidoc
  articles/routing/nested-views.asciidoc
  articles/routing/url-parameters.asciidoc
Labels: AsciiDoc OK

#1130 Charts update
  articles/ds/components/charts/basic-use.asciidoc
  articles/ds/components/charts/charttypes.asciidoc
  articles/ds/components/charts/configuration.asciidoc
  articles/ds/components/charts/css-styling.asciidoc
  articles/ds/components/charts/data.asciidoc
  articles/ds/components/charts/figma-library.asciidoc
  articles/ds/components/charts/img/charts-3d-distance.png
  articles/ds/components/charts/img/charts-3d-pie.png
  articles/ds/components/charts/img/charts-3d-scatter.png
  articles/ds/components/charts/img/charts-arearange.png
  articles/ds/components/charts/img/charts-axes-lo.png
  articles/ds/components/charts/img/charts-boxplot.png
  articles/ds/components/charts/img/charts-bubble.png
  articles/ds/components/charts/img/charts-bullet.png
  articles/ds/components/charts/img/charts-candlestick.png
  articles/ds/components/charts/img/charts-configuration-legend.png
  articles/ds/components/charts/img/charts-dataprovider.png
  articles/ds/components/charts/img/charts-donut.png
  articles/ds/components/charts/img/charts-drilldown-details.png
  articles/ds/components/charts/img/charts-elements-lo.png
  articles/ds/components/charts/img/charts-errorbar.png
  articles/ds/components/charts/img/charts-flags.png
  articles/ds/components/charts/img/charts-funnel.png
  articles/ds/components/charts/img/charts-gauge.png
  articles/ds/components/charts/img/charts-heatmap.png
  articles/ds/components/charts/img/charts-ohlc.png
  articles/ds/components/charts/img/charts-organization.png
  articles/ds/components/charts/img/charts-overview.png
  articles/ds/components/charts/img/charts-pie.png
  articles/ds/components/charts/img/charts-polarspiderweb.png
  articles/ds/components/charts/img/charts-polygon.png
  articles/ds/components/charts/img/charts-scatter.png
  articles/ds/components/charts/img/charts-solidgauge.png
  articles/ds/components/charts/img/charts-timeline.png
  articles/ds/components/charts/img/charts-treemap.png
  articles/ds/components/charts/img/charts-twodimensional.png
  articles/ds/components/charts/img/charts-waterfall.png
  articles/ds/components/charts/img/charts-xrange.png
  articles/ds/components/charts/img/css-styling1.png
  articles/ds/components/charts/img/css-styling2.png
  articles/ds/components/charts/img/timeline_charts_compare.png
  articles/ds/components/charts/img/timeline_intro_screen.png
  articles/ds/components/charts/index.asciidoc
  articles/ds/components/charts/installing.asciidoc
  articles/ds/components/charts/java-api/index.asciidoc
  articles/ds/components/charts/migrating-from-earlier-versions.asciidoc
  articles/ds/components/charts/svg-generator.asciidoc
  articles/ds/components/charts/timeline.asciidoc
  frontend/demo/component/charts/charts-overview.ts
Labels: AsciiDoc

#1110 EL improvements: Hilla / "Creating an Application", Routing, Forms, Security
  .github/styles/Vocab/Docs/accept.txt
  articles/application/accessing-backend.asciidoc
  articles/application/basics.asciidoc
  articles/application/components.asciidoc
  articles/application/configuring.asciidoc
  articles/application/error-handling.asciidoc
  articles/application/events.asciidoc
  articles/application/index.asciidoc
  articles/application/lit.asciidoc
  articles/application/state-management.asciidoc
  articles/css/shadow-dom.asciidoc
  articles/css/styling-with-css.asciidoc
  articles/css/utility-classes.asciidoc
  articles/data-binding/binder-load.asciidoc
  articles/data-binding/binder-validation.asciidoc
  articles/data-binding/binder.asciidoc
  articles/data-binding/binding-arrays.asciidoc
  articles/data-binding/form-images.asciidoc
  articles/data-binding/form-status-tracking.asciidoc
  articles/data-binding/reference.asciidoc
  articles/data-binding/vaadin-components.asciidoc
  articles/data-binding/web-component-field-strategy.asciidoc
  articles/routing/defining.asciidoc
  articles/routing/layouts.asciidoc
  articles/routing/navigation-lifecycle.asciidoc
  articles/routing/nested-views.asciidoc
  articles/routing/router.asciidoc
  articles/routing/url-parameters.asciidoc
  articles/security/authentication-offline.asciidoc
  articles/security/authentication.asciidoc
  articles/security/best-practices.asciidoc
  articles/security/configuring.asciidoc
  articles/security/handle-session-expiration.asciidoc
  articles/security/index.asciidoc
  articles/security/intro.asciidoc
  articles/security/role-based-access.asciidoc
  articles/security/spring-login.asciidoc
  articles/security/spring-stateless.asciidoc
  articles/security/vulnerabilities.asciidoc
Labels: AsciiDoc OK

#1137 Add documentation for interpolateMessageCallback (Hilla 1.0) (#1015)
  articles/data-binding/binder-validation.asciidoc
Labels: AsciiDoc, hilla

#1133 Remove Hilla-specific upgrade instructions away from common
  articles/upgrading/common/_22-23.adoc
  articles/upgrading/fusion/_22-23.adoc
Labels: AsciiDoc OK

#1139 Docs/charts upgrade guide
  articles/upgrading/flow/_16-17.adoc
  articles/upgrading/flow/_22-23.adoc
Labels: AsciiDoc OK

#1135 Create classic-components.asciidoc
  .github/styles/Vocab/Docs/accept.txt
  articles/flow/advanced/classic-components.asciidoc
Labels: AsciiDoc OK

#1096 Add note about `vaadin.launch-browser`
  articles/flow/integrations/spring/configuration.asciidoc
Labels: AsciiDoc OK

#1155 Fix incorrect file path
  articles/flow/tutorial/_heroku-steps.adoc
Labels: AsciiDoc OK

#1165 Copy v14-23 to a separate hidden page
  .github/.vale-pr.ini
  articles/v14-23-upgrade/index.asciidoc
  articles/v14-23-upgrade/instructions/_after-upgrade.adoc
  articles/v14-23-upgrade/instructions/_common.adoc
  articles/v14-23-upgrade/instructions/_styling.adoc
  articles/v14-23-upgrade/instructions/_typescript.adoc
Labels: AsciiDoc OK

#1173 Upgrade guide: Added notes about slotted item contents in CB and Select
  articles/upgrading/styling/_21-22.adoc
  articles/v14-23-upgrade/essential-steps/instructions/_styling.adoc
Labels: AsciiDoc

#1175 fix: Fix them document loading order.
  articles/ds/customization/custom-theme.asciidoc
Labels: AsciiDoc OK

#1168 Update data-provider.asciidoc
  articles/flow/binding-data/data-provider.asciidoc
Labels: AsciiDoc

#1138 English-lang improvements to Hilla documentation
  articles/advanced/client-middleware.asciidoc
  articles/advanced/components-definitions.asciidoc
  articles/advanced/connection-indicator.asciidoc
  articles/advanced/custom-serialization.asciidoc
  articles/advanced/endpoints-generator.asciidoc
  articles/advanced/endpoints-method-validation.asciidoc
  articles/advanced/endpoints-urls.asciidoc
  articles/advanced/type-conversion.asciidoc
  articles/advanced/typescript-client.asciidoc
Labels: AsciiDoc OK

#1181 Mention PageConfiguration obsolete API
  articles/v14-23-upgrade/final-steps/index.adoc
Labels: AsciiDoc OK

#1182 Remove mention of AppShellRegistry::getTitle
  articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
Labels: AsciiDoc OK

#1177 Docs/upgrade guide expandable sections
  articles/v14-23-upgrade/essential-steps/index.adoc
  articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
  articles/v14-23-upgrade/essential-steps/instructions/_styling.adoc
  articles/v14-23-upgrade/essential-steps/instructions/_typescript.adoc
Labels: AsciiDoc OK

#1188 Document necessary Spring security config changes when migrating to V23
  articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
  articles/v14-23-upgrade/final-steps/index.adoc
Labels: AsciiDoc OK

#1191 Remove link to gitpod from quick start tutorial
  articles/flow/guide/quick-start.adoc
Labels: AsciiDoc OK

#1195 Docs/v14 23 charts old theme module
  articles/upgrading/flow/_22-23.adoc
  articles/v14-23-upgrade/essential-steps/instructions/_styling.adoc
Labels: AsciiDoc

#1187 Add source control instructions
  articles/flow/configuration/source-control.adoc
  articles/v14-23-upgrade/final-steps/index.adoc
Labels: AsciiDoc

#1210 docs: document using short package names
  articles/v14-23-upgrade/final-steps/index.adoc
  articles/v14-23-upgrade/final-steps/instructions/_typescript.adoc
Labels: AsciiDoc

#1213 English-lang improvements to source control instructions.
  articles/flow/configuration/source-control.adoc
  articles/v14-23-upgrade/final-steps/index.adoc
Labels: AsciiDoc OK

#1217 docs: document replacing iron components
  articles/v14-23-upgrade/final-steps/index.adoc
  articles/v14-23-upgrade/final-steps/instructions/_iron.adoc
Labels: AsciiDoc

#1209 Add note about router-ignore attribute
  articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
Labels: AsciiDoc OK

#1200 English-lang improvements to Hilla Production documentation.
  articles/production/cloud-providers/aws/index.adoc
  articles/production/cloud-providers/azure/index.adoc
  articles/production/cloud-providers/google/index.adoc
  articles/production/cloud-providers/index.adoc
  articles/production/overview.asciidoc
  articles/production/servlet-containers.asciidoc
  articles/production/spring-boot.asciidoc
  articles/production/troubleshooting.asciidoc
  articles/pwa/cache-client-side-data.asciidoc
  articles/pwa/offline-authentication-check.asciidoc
Labels: AsciiDoc OK

#1218 refactor: update map examples to remove fluent API usage
  src/main/java/com/vaadin/demo/component/map/Icons.java
  src/main/java/com/vaadin/demo/component/map/MapEvents.java
  src/main/java/com/vaadin/demo/component/map/MapLayers.java
  src/main/java/com/vaadin/demo/component/map/MapMarkers.java
  src/main/java/com/vaadin/demo/component/map/MapSources.java
Labels: AsciiDoc, design system

#1221 docs: Update Quarkus Live Reload documentation
  articles/flow/integrations/quarkus.asciidoc
Labels: AsciiDoc OK

#1225 Add note about the removal of PWA::enableInstallPrompt
  articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
Labels: AsciiDoc OK

#1223 Remove lit-html 1 to 2 instructions from V14 -> 23 upgrade instructions
  articles/v14-23-upgrade/essential-steps/instructions/_typescript.adoc
Labels: AsciiDoc OK

#1232 Docs/upgrade guide styling stuff
  articles/upgrading/styling/_21-22.adoc
  articles/v14-23-upgrade/essential-steps/instructions/_styling.adoc
Labels: AsciiDoc

#1224 Add note about BootstrapListener deprecation in V23
  articles/v14-23-upgrade/final-steps/index.adoc
Labels: AsciiDoc OK

#1242 Suggest useDeprecatedV14Bootstrapping in essential v14-23 upgrade steps
  articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
  articles/v14-23-upgrade/final-steps/index.adoc
Labels: AsciiDoc OK

#1237 docs: document migrating from PolymerTemplate
  articles/v14-23-upgrade/final-steps/index.adoc
  articles/v14-23-upgrade/final-steps/instructions/_polymertemplate.adoc
Labels: AsciiDoc

#1238 Instructions for migrating to custom theme folder
  articles/v14-23-upgrade/essential-steps/instructions/_styling.adoc
  articles/v14-23-upgrade/final-steps/index.adoc
Labels: AsciiDoc

#1246 Reference Vaadin 14 to 23 upgrade instructions from upgrade tool
  articles/upgrading/index.adoc
  frontend/demo/upgrade-tool/upgrade-tool.ts
Labels: AsciiDoc

#1247 docs: add a note about a cyclic dependency in V14 bakery
  articles/v14-23-upgrade/essential-steps/instructions/_common.adoc
Labels: AsciiDoc

#1249 docs: document migrating from template to renderer
  articles/v14-23-upgrade/final-steps/instructions/_polymertemplate.adoc
Labels: AsciiDoc
