Repository vaadin/docs, pull requests merged in 2022-10, with the labels that each got.

#1778 Remove mention of sticky sessions
  articles/production/cloud-providers/index.adoc
Labels: Language not checked

#1781 docs: fix DX findings for TabSheet and Tooltip
  articles/components/grid/index.asciidoc
  articles/components/menu-bar/index.asciidoc
  articles/components/tabs/index.asciidoc
  articles/components/tooltip/index.asciidoc
  frontend/demo/component/tooltip/tooltip-positioning.ts
Labels: Language checked

#1784 docs: add tabsheet bordered theme variant example
  articles/components/tabs/index.asciidoc
  frontend/demo/component/tabs/tabsheet-theme-bordered.ts
  src/main/java/com/vaadin/demo/component/tabs/TabSheetThemeBordered.java
Labels: Language not checked

#1787 docs: add TS example for configuring tooltip delays
  articles/components/tooltip/index.asciidoc
Labels: Language not checked

#1697 Documentation for Observability Kit
  .github/styles/Vaadin/ComplexWords.yml
  .github/styles/Vaadin/ProductName.yml
  .github/styles/Vaadin/Terms.yml
  .github/styles/Vaadin/TooWordy.yml
  .github/styles/Vaadin/Weasel.yml
  .github/styles/Vocab/Docs/accept.txt
  articles/_images/observability-kit.svg
  articles/index.asciidoc
  articles/tools/index.asciidoc
  articles/tools/observability/_download-agent.asciidoc
  articles/tools/observability/configuration.asciidoc
  articles/tools/observability/customization.asciidoc
  articles/tools/observability/getting-started.asciidoc
  articles/tools/observability/index.asciidoc
  articles/tools/observability/integrations/_run-app.asciidoc
  articles/tools/observability/integrations/datadog.asciidoc
  articles/tools/observability/integrations/grafana.asciidoc
  articles/tools/observability/integrations/index.asciidoc
  articles/tools/observability/integrations/jaeger-prometheus.asciidoc
  articles/tools/observability/integrations/newrelic.asciidoc
  articles/tools/observability/reference.asciidoc
  dspublisher/theme/global.css
  frontend/demo/tools/observability/newrelic/dashboard-generator.ts
  frontend/demo/tools/observability/newrelic/dashboard-template.json
Labels: Language checked

#1729 Explain how to use form binder in dialogs
  articles/data-binding/binder.asciidoc
  frontend/demo/fusion/forms/dialogs/newsletter-dialog.ts
  src/main/java/com/vaadin/demo/fusion/forms/dialogs/NewsletterEndpoint.java
  src/main/java/com/vaadin/demo/fusion/forms/dialogs/NewsletterSubscription.java
Labels: hilla, Language checked

#1775 chore: added feature flags documentation
  .github/styles/Vaadin/Abbr.yml
  .github/styles/Vaadin/ComplexWords.yml
  .github/styles/Vocab/Docs/accept.txt
  articles/components/map/index.asciidoc
  articles/configuration/feature-flags.adoc
  articles/configuration/live-reload/index.asciidoc
  articles/configuration/properties.asciidoc
  articles/tools/ce/advanced/backend-api.asciidoc
Labels: flow, Language not checked

#1791 chore: fix DemoExporter hidden lines formatting
  src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsVerticalLayout.java
  src/main/java/com/vaadin/demo/component/checkbox/CheckboxCustomPresentation.java
  src/main/java/com/vaadin/demo/component/cookieconsent/CookieConsentBasic.java
  src/main/java/com/vaadin/demo/component/cookieconsent/CookieConsentLocalization.java
  src/main/java/com/vaadin/demo/component/cookieconsent/CookieConsentTheming.java
  src/main/java/com/vaadin/demo/component/datepicker/DatePickerCustomValidation.java
  src/main/java/com/vaadin/demo/component/datepicker/DatePickerDateFormatIndicator.java
  src/main/java/com/vaadin/demo/component/datepicker/DatePickerIndividualInputFields.java
  src/main/java/com/vaadin/demo/component/datepicker/DatePickerInitialPosition.java
  src/main/java/com/vaadin/demo/component/datepicker/DatePickerInternationalization.java
  src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerCustomValidation.java
  src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerInitialPosition.java
  src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerInputFormat.java
  src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerInternationalization.java
  src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerMinutesStep.java
  src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerSecondsStep.java
  src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerWeekNumbers.java
  src/main/java/com/vaadin/demo/component/dialog/DialogBasic.java
  src/main/java/com/vaadin/demo/component/dialog/DialogClosing.java
  src/main/java/com/vaadin/demo/component/dialog/DialogDraggable.java
  src/main/java/com/vaadin/demo/component/dialog/DialogFooter.java
  src/main/java/com/vaadin/demo/component/dialog/DialogHeader.java
  src/main/java/com/vaadin/demo/component/dialog/DialogResizable.java
  src/main/java/com/vaadin/demo/component/gridpro/GridProThemeHighlightEditableCells.java
  src/main/java/com/vaadin/demo/component/gridpro/GridProThemeHighlightReadOnlyCells.java
  src/main/java/com/vaadin/demo/component/listbox/ListBoxCustomItemPresentation.java
  src/main/java/com/vaadin/demo/component/login/LoginAdditionalInformation.java
  src/main/java/com/vaadin/demo/component/login/LoginBasic.java
  src/main/java/com/vaadin/demo/component/login/LoginInternationalization.java
  src/main/java/com/vaadin/demo/component/login/LoginOverlayBasic.java
  src/main/java/com/vaadin/demo/component/login/LoginOverlayHeader.java
  src/main/java/com/vaadin/demo/component/login/LoginOverlayInternationalization.java
  src/main/java/com/vaadin/demo/component/login/LoginRichContent.java
  src/main/java/com/vaadin/demo/component/login/LoginValidation.java
  src/main/java/com/vaadin/demo/component/map/MapBasic.java
  src/main/java/com/vaadin/demo/component/map/MapEvents.java
  src/main/java/com/vaadin/demo/component/map/MapLayers.java
  src/main/java/com/vaadin/demo/component/map/MapMarkers.java
  src/main/java/com/vaadin/demo/component/map/MapSources.java
  src/main/java/com/vaadin/demo/component/map/MapThemeBorderless.java
  src/main/java/com/vaadin/demo/component/map/MapViewport.java
  src/main/java/com/vaadin/demo/component/messages/MessageListWithThemeComponent.java
  src/main/java/com/vaadin/demo/component/numberfield/NumberFieldStepperControls.java
  src/main/java/com/vaadin/demo/component/progressbar/ProgressBarCompletionTime.java
  src/main/java/com/vaadin/demo/component/progressbar/ProgressBarIndeterminate.java
  src/main/java/com/vaadin/demo/component/progressbar/ProgressBarThemeVariants.java
  src/main/java/com/vaadin/demo/component/splitlayout/SplitLayoutInitialSplitterPosition.java
  src/main/java/com/vaadin/demo/component/splitlayout/SplitLayoutMinimalThemeVariants.java
  src/main/java/com/vaadin/demo/component/splitlayout/SplitLayoutThemeVariants.java
  src/main/java/com/vaadin/demo/component/timepicker/TimePickerCustomValidation.java
  src/main/java/com/vaadin/demo/component/tooltip/TooltipPositioning.java
  src/main/java/com/vaadin/demo/component/treegrid/TreeGridBasic.java
  src/main/java/com/vaadin/demo/component/treegrid/TreeGridColumn.java
  src/main/java/com/vaadin/demo/component/treegrid/TreeGridRichContent.java
Labels: Language not checked

#1715 SSO Kit documentation
  .github/styles/Vaadin/Abbr.yml
  .github/styles/Vocab/Docs/accept.txt
  articles/index.asciidoc
  articles/security/enabling-security.adoc
  articles/tools/index.asciidoc
  articles/tools/sso/getting-started.adoc
  articles/tools/sso/index.asciidoc
  articles/tools/sso/theming.asciidoc
  frontend/themes/docs/keycloak-theme-example.css
  pom.xml
  src/main/java/com/vaadin/demo/sso/ProfileView.java
  src/main/resources/application.properties
Labels: Language not checked

#1798 update MPR limitation page regarding V7 and V8 versions
  articles/tools/mpr/configuration/limitations.asciidoc
Labels: Language not checked

#1789 Add an article describing the new Hilla multi-module engine
  articles/advanced/multimodule.asciidoc
Labels: hilla, Language checked

#1807 chore: various small fixes for Hilla docs
  articles/data-binding/reference.asciidoc
  articles/data-binding/vaadin-components.asciidoc
  articles/getting-started.asciidoc
  articles/routing/nested-views.asciidoc
  articles/routing/router.asciidoc
  articles/tutorials/basics-tutorial.asciidoc
  articles/tutorials/quickstart.asciidoc
  frontend/demo/fusion/components/color-picker-view.ts
  frontend/demo/fusion/forms/dialogs/newsletter-dialog.ts
Labels: Language not checked

#1808 chore: update components TS definitions article
  articles/advanced/components-definitions.asciidoc
Labels: Language not checked

#1804 fix: some fixes for using components in Hilla
  articles/application/components.asciidoc
Labels: Language checked
