Repository vaadin/docs, pull requests merged in 2023-08, with the labels that each got.

#2616 delay server calls until login info is ready
  articles/lit/start/in-depth/login-and-authentication.adoc
Labels: Language unchecked

#2569 Mention Microsoft Entra ID
  .github/styles/Vocab/Docs/accept.txt
  articles/tools/sso/index.asciidoc
  articles/tools/sso/integrations/azure-ad.asciidoc
Labels: Language checked

#2610 Clarify that it's the O11y example that is not production-ready
  articles/tools/observability/integrations/jaeger-prometheus.asciidoc
Labels: Language checked

#2482 Upgrade quick start tutorial
  articles/guide/index.asciidoc
  articles/guide/quick-start.adoc
  articles/guide/start/index.asciidoc
  articles/guide/step-by-step/index.asciidoc
Labels: Language checked

#2643 chore: remove no longer used components example files
  frontend/demo/component/checkbox/checkbox-custom-presentation.ts
  frontend/demo/component/checkbox/checkbox-edit-multiple.ts
  frontend/demo/component/combobox/combo-box-placeholder.ts
  frontend/demo/component/emailfield/email-field-pattern.ts
  frontend/demo/component/textfield/text-field-allowed-char-pattern.ts
  frontend/demo/component/textfield/text-field-clear-button.ts
  frontend/demo/component/textfield/text-field-min-max-input-length.ts
  frontend/demo/component/textfield/text-field-pattern.ts
  frontend/demo/component/textfield/text-field-placeholder.ts
  frontend/demo/component/textfield/text-field-prefix-suffix.ts
  frontend/demo/component/textfield/text-field-small-variant.ts
  frontend/demo/component/textfield/text-field-text-alignment.ts
  frontend/demo/component/timepicker/time-picker-parsing.ts
  src/main/java/com/vaadin/demo/component/checkbox/CheckboxCustomPresentation.java
  src/main/java/com/vaadin/demo/component/checkbox/CheckboxEditMultiple.java
  src/main/java/com/vaadin/demo/component/combobox/ComboBoxPlaceholder.java
  src/main/java/com/vaadin/demo/component/emailfield/EmailFieldPattern.java
  src/main/java/com/vaadin/demo/component/textfield/TextFieldAllowedCharPattern.java
  src/main/java/com/vaadin/demo/component/textfield/TextFieldClearButton.java
  src/main/java/com/vaadin/demo/component/textfield/TextFieldMinMaxInputLength.java
  src/main/java/com/vaadin/demo/component/textfield/TextFieldPattern.java
  src/main/java/com/vaadin/demo/component/textfield/TextFieldPlaceholder.java
  src/main/java/com/vaadin/demo/component/textfield/TextFieldPrefixSuffix.java
  src/main/java/com/vaadin/demo/component/textfield/TextFieldSmallVariant.java
  src/main/java/com/vaadin/demo/component/textfield/TextFieldTextAlignment.java
  src/main/java/com/vaadin/demo/component/timepicker/TimePickerParsing.java
Labels: Language unchecked

#2611 Incremental builds for Gradle vaadinPrepareFrontend task
  articles/guide/start/gradle.asciidoc
Labels: Language checked

#2662 Gradle plugin docs minor updates
  articles/guide/start/_images/gradle-project-created-annotated.png
  articles/guide/start/gradle.asciidoc
Labels: Language checked

#2618 docs: add Web Storage server-side API documentation
  articles/advanced/web-storage-api.asciidoc
  frontend/themes/docs/theme-editor.css
  package-lock.json
Labels: Language checked

#2678 Clarifying font file location
  articles/styling/application-theme.adoc
Labels: Language checked

#2619 fix: Update webPush documentation
  .github/styles/Vocab/Docs/accept.txt
  articles/configuration/setting-up-webpush.adoc
Labels: Language checked

#2624 docs: update mixins documentation
  articles/create-ui/creating-components/mixins.asciidoc
Labels: Language checked

#2626 docs: added info on disabled live reload while working with Theme Editor
  articles/tools/theme-editor/index.asciidoc
Labels: Language checked

#2704 docs: add documentation for applyTheme function
  articles/create-ui/templates/styling-templates.asciidoc
Labels: Language checked

#2724 docs: Form Filler article included
  .github/styles/Vaadin/Abbr.yml
  articles/tools/formfiller/images/formfiller-design.png
  articles/tools/formfiller/images/simple-example.png
  articles/tools/formfiller/index.asciidoc
  articles/tools/index.asciidoc
Labels: Language unchecked

#2725 AI Form Filler doc URL changed
  articles/tools/ai-form-filler/images/formfiller-design.png
  articles/tools/ai-form-filler/images/simple-example.png
  articles/tools/ai-form-filler/index.asciidoc
  articles/tools/index.asciidoc
Labels: Language unchecked

#2693 Expand description of type conversion for Instant and Date
  articles/lit/reference/type-conversion.adoc
Labels: Language unchecked

#2711 Create using-minifinder
  .github/styles/Vaadin/JustSimply.yml
  .github/styles/Vocab/Docs/accept.txt
  articles/advanced/using-minifinder.adoc
Labels: Language checked

#2715 Clarify Vaadin security key and push ID tokens
  .github/styles/Vaadin/Abbr.yml
  .github/styles/Vocab/Docs/accept.txt
  articles/security/advanced-topics/vulnerabilities.asciidoc
Labels: Language checked

#2723 feat: add react form guides
  articles/lit/guides/forms/binder-load.adoc
  articles/lit/guides/forms/binder-load.asciidoc
  articles/lit/guides/forms/binder-validation.adoc
  articles/lit/guides/forms/binder.adoc
  articles/lit/guides/forms/binding-arrays.adoc
  articles/lit/guides/forms/form-images.adoc
  articles/lit/guides/forms/form-status-tracking.adoc
  articles/lit/guides/forms/index.adoc
  articles/lit/guides/forms/vaadin-components.adoc
  articles/react/guides/forms/binder-load.adoc
  articles/react/guides/forms/binder-validation.adoc
  articles/react/guides/forms/binder.adoc
  articles/react/guides/forms/binding-arrays.adoc
  articles/react/guides/forms/form-images.adoc
  articles/react/guides/forms/form-status-tracking.adoc
  articles/react/guides/forms/index.adoc
  articles/react/guides/forms/vaadin-components.adoc
Labels: Language unchecked

#2738 Update Hilla form field strategy example
  frontend/demo/fusion/forms/field-strategy/my-text-field-strategy.ts
Labels: hilla, examples

#2535 Minor Clean-Up: Tools - SSO
  .github/styles/Vocab/Docs/accept.txt
  articles/tools/sso/getting-started.adoc
  articles/tools/sso/index.asciidoc
  articles/tools/sso/integrations/azure-ad.asciidoc
  articles/tools/sso/integrations/keycloak.asciidoc
  articles/tools/sso/integrations/okta.asciidoc
  articles/tools/sso/theming.asciidoc
Labels: Language checked

#2734 Add Descriptions: configuration to create-ui
  articles/configuration/live-reload/cdi.asciidoc
  articles/configuration/live-reload/hotswap-agent.asciidoc
  articles/configuration/live-reload/jetty.asciidoc
  articles/configuration/live-reload/jrebel.asciidoc
  articles/configuration/live-reload/spring-boot.asciidoc
  articles/contributing/docs/word-list.asciidoc
  articles/create-ui/creating-components/property-descriptor.asciidoc
  articles/create-ui/templates/and-binder.asciidoc
  articles/create-ui/templates/basic.asciidoc
  articles/create-ui/templates/component-integration.asciidoc
  articles/create-ui/templates/components-in-slot.asciidoc
  articles/create-ui/templates/components.asciidoc
  articles/create-ui/templates/index.asciidoc
  articles/create-ui/templates/limitations.asciidoc
  articles/create-ui/templates/polymer/bindings.asciidoc
  articles/create-ui/templates/polymer/event-handlers.asciidoc
  articles/create-ui/templates/polymer/index.asciidoc
  articles/create-ui/templates/polymer/list-bindings.asciidoc
  articles/create-ui/templates/polymer/model-bean.asciidoc
  articles/create-ui/templates/polymer/model-encoders.asciidoc
  articles/create-ui/templates/polymer/parent-layout.asciidoc
  articles/create-ui/templates/polymer/polymer-template-and-binder.asciidoc
  articles/create-ui/templates/polymer/polymer-template-basic.asciidoc
  articles/create-ui/templates/polymer/polymer-template-components-in-slot.asciidoc
  articles/create-ui/templates/styling-templates.asciidoc
  articles/create-ui/templates/subtemplate.asciidoc
  articles/create-ui/web-components/an-in-project-web-component.asciidoc
  articles/create-ui/web-components/debugging-a-web-component-integration.asciidoc
  articles/create-ui/web-components/index.asciidoc
  articles/create-ui/web-components/introduction-to-webcomponents.asciidoc
  articles/create-ui/web-components/java-api-for-a-web-component.asciidoc
Labels: Language checked

#2733 add reference.adoc for react
  articles/lit/guides/forms/reference.adoc
  articles/react/guides/forms/reference.adoc
Labels: Language unchecked

#2750 fix: Change session Id on login
  articles/security/advanced-topics/securing-plain-java-app.adoc
Labels: Language checked
