Repository vaadin/docs, pull requests merged in 2023-05, with the labels that each got.

#2410 Fix broken images
  articles/react/guides/production/cloud-providers/aws/images/aws-deploy-success.png
  articles/react/guides/production/cloud-providers/azure/images/azure-choices.png
  articles/react/guides/production/cloud-providers/azure/images/azure-deploy-success.png
  articles/react/guides/production/cloud-providers/heroku/images/heroku-create-success.png
Labels: hilla

#2409 Improve Hilla SEO
  articles/lit/components/index.adoc
  articles/lit/guides/styling.adoc
  articles/lit/start/basics/index.adoc
  articles/lit/start/faq.adoc
  articles/react/components/index.adoc
  articles/react/guides/styling.adoc
Labels: hilla

#2396 Add Upgrade Notes for Hilla 2 (PR 2226)
  articles/lit/guides/upgrading/_styling.adoc
  articles/lit/guides/upgrading/index.adoc
  articles/react/guides/upgrading/index.adoc
Labels: hilla, Language checked

#2381 Upgrade to v24 - PR 1907 Language Check
  articles/upgrading/index.adoc
Labels: Language checked

#2414 docs: new map features
  articles/components/map/index.asciidoc
  frontend/demo/component/map/map-marker-drag-drop.ts
  frontend/demo/component/map/map-marker-text.ts
  src/main/java/com/vaadin/demo/component/map/Icons.java
  src/main/java/com/vaadin/demo/component/map/MapEvents.java
  src/main/java/com/vaadin/demo/component/map/MapMarkerDragDrop.java
  src/main/java/com/vaadin/demo/component/map/MapMarkerText.java
  src/main/java/com/vaadin/demo/component/map/MapMarkers.java
Labels: Language checked

#2397 Add Polymer Addon Setup Instructions - PR2251
  articles/create-ui/templates/polymer/bindings.asciidoc
  articles/create-ui/templates/polymer/event-handlers.asciidoc
  articles/create-ui/templates/polymer/index.asciidoc
  articles/create-ui/templates/polymer/list-bindings.asciidoc
  articles/create-ui/templates/polymer/model-bean.asciidoc
  articles/create-ui/templates/polymer/model-encoders.asciidoc
  articles/create-ui/templates/polymer/parent-layout.asciidoc
  articles/create-ui/templates/polymer/polymer-template-and-binder.asciidoc
  articles/create-ui/templates/polymer/polymer-template-basic.asciidoc
  articles/create-ui/templates/polymer/polymer-template-components-in-slot.asciidoc
Labels: Language checked

#2362 docs: grid lazy column rendering mode documentation
  articles/components/grid/index.asciidoc
  frontend/demo/component/grid/grid-lazy-column-rendering.ts
  src/main/java/com/vaadin/demo/component/grid/GridLazyColumnRendering.java
Labels: Language checked

#2417 Update properties.asciidoc
  .github/styles/Vocab/Docs/accept.txt
  articles/configuration/properties.asciidoc
Labels: Language checked

#2405 Docs/minor dsp, ds and styling docs fixes
  articles/components/charts/migrating-from-earlier-versions.asciidoc
  articles/components/grid/index.asciidoc
  articles/components/grid/styling.asciidoc
  articles/styling/advanced/shadow-dom-styling.adoc
  articles/tools/dspublisher/troubleshooting.adoc
  src/main/java/com/vaadin/demo/component/grid/GridStyling.java
Labels: Language checked

#2386 feat(hilla): document Tree Grid and Multi-Select Combo Box
  articles/react/components/multi-select-combo-box/index.adoc
  articles/react/components/tree-grid/index.adoc
Labels: Language checked

#2431 Update Charts migration guide
  articles/components/charts/migrating-from-earlier-versions.asciidoc
Labels: Language checked

#2419 Add compatibility matrix for V24
  articles/compatibility.adoc
Labels: Language checked

#2404 Docs/bundle and shadow css caveat
  articles/configuration/development-mode/index.asciidoc
  articles/styling/advanced/shadow-dom-styling.adoc
  articles/styling/application-theme.adoc
Labels: Language checked

#2430 Input Fields Common Features (PR 2337)
  articles/components/_input-field-common-features.adoc
  articles/components/button/index.asciidoc
  articles/components/checkbox/index.asciidoc
  articles/components/combo-box/index.asciidoc
  articles/components/custom-field/index.asciidoc
  articles/components/date-picker/index.asciidoc
  articles/components/date-time-picker/index.asciidoc
  articles/components/email-field/index.asciidoc
  articles/components/index.asciidoc
  articles/components/password-field/index.asciidoc
  articles/components/radio-button/index.asciidoc
  articles/components/select/index.asciidoc
  articles/components/text-area/index.asciidoc
  articles/components/text-field/index.asciidoc
  articles/components/time-picker/index.asciidoc
  articles/styling/styling-components/sharing-styles.adoc
Labels: Language checked

#2432 PR2296-Add React Components to Hilla - A to B
  articles/react/components/accordion/index.adoc
  articles/react/components/app-layout/index.adoc
  articles/react/components/avatar/index.adoc
  articles/react/components/board/index.adoc
  articles/react/components/button/index.adoc
Labels: Language checked

#2433 PR2296-Add React Components to Hilla - C
  articles/react/components/charts/index.adoc
  articles/react/components/checkbox/index.adoc
  articles/react/components/combo-box/index.adoc
  articles/react/components/confirm-dialog/index.adoc
  articles/react/components/context-menu/index.adoc
  articles/react/components/cookie-consent/index.adoc
  articles/react/components/crud/index.adoc
  articles/react/components/custom-field/index.adoc
Labels: Language checked

#2437 PR2296-Add React Components to Hilla - D to F
  articles/react/components/date-picker/index.adoc
  articles/react/components/date-time-picker/index.adoc
  articles/react/components/details/index.adoc
  articles/react/components/dialog/index.adoc
  articles/react/components/email-field/index.adoc
  articles/react/components/form-layout/index.adoc
Labels: Language checked

#2440 PR2296-Add React Components to Hilla - L to M
  articles/react/components/list-box/index.adoc
  articles/react/components/login/index.adoc
  articles/react/components/menu-bar/index.adoc
  articles/react/components/message-input/index.adoc
  articles/react/components/message-list/index.adoc
Labels: Language checked

#2445 PR2296-Add React Components to Hilla - N to R
  articles/react/components/multi-select-combo-box/index.adoc
  articles/react/components/notification/index.adoc
  articles/react/components/number-field/index.adoc
  articles/react/components/password-field/index.adoc
  articles/react/components/progress-bar/index.adoc
  articles/react/components/radio-button/index.adoc
  articles/react/components/rich-text-editor/index.adoc
Labels: Language checked

#2448 PR2296-Add React Components to Hilla - S to Text
  articles/react/components/scroller/index.adoc
  articles/react/components/select/index.adoc
  articles/react/components/split-layout/index.adoc
  articles/react/components/tabs/index.adoc
  articles/react/components/text-area/index.adoc
  articles/react/components/text-field/index.adoc
Labels: Language checked

#2451 PR2296-Add React Components to Hilla - Time to Z
  articles/react/components/time-picker/index.adoc
  articles/react/components/tooltip/index.adoc
  articles/react/components/tree-grid/index.adoc
  articles/react/components/upload/index.adoc
  articles/react/components/vertical-layout/index.adoc
  articles/react/components/virtual-list/index.adoc
Labels: Language checked

#2443 fix checkbox label in react todo demo
  articles/lit/start/basics/index.adoc
Labels: hilla

#2455 Edits to Components Files - Time to Z
  articles/components/time-picker/index.asciidoc
  articles/components/tooltip/index.asciidoc
  articles/components/tree-grid/index.asciidoc
  articles/components/upload/index.asciidoc
  articles/components/vertical-layout/index.asciidoc
  articles/components/virtual-list/index.asciidoc
Labels: Language checked

#2460 PR2066 - Breaking Changes Added to Upgrade Guide
  articles/upgrading/index.adoc
Labels: Language checked
