Repository vaadin/docs, pull requests merged in 2023-02, with the labels that each got.

#2069 New title for endpoint access control
  README.md
  articles/lit/guides/security/configuring.adoc
  articles/react/guides/security/configuring.adoc
Labels: Language not checked

#2062 Improving lazy data binding docs
  articles/binding-data/data-provider.asciidoc
Labels: Language not checked

#2070 Docs/component index redesign
  articles/components/_images/accessibility-symbol.svg
  articles/components/_images/cat-dataentry.svg
  articles/components/_images/cat-layouts.svg
  articles/components/_images/cat-vizandix.svg
  articles/components/index.asciidoc
Labels: Language not checked

#2066 Components breaking changes added to V24 upgrade guide
  articles/upgrading/V23-V24-steps/_styling.adoc
  articles/upgrading/V23-V24-steps/index.adoc
  dspublisher/theme/global.css
Labels: Language not checked

#2067 Update contribution instructions
  README.md
  articles/contributing-docs/authoring/content-guidelines.asciidoc
Labels: Language not checked

#2073 chore: add missing horizontal-layout import to demo
  frontend/demo/component/notification/notification-rich.ts
Labels: Language not checked

#2018 feat: Express Build mode
  articles/components/charts/svg-generator.asciidoc
  articles/configuration/development-mode/index.asciidoc
  articles/configuration/development-mode/node-js.asciidoc
  articles/configuration/development-mode/npm-pnpm.asciidoc
  articles/configuration/node-js.asciidoc
  articles/upgrading/upgrade-tool/common/_22-23.adoc
Labels: Language checked

#2096 fix: use correct link for image
  articles/lit/start/in-depth/application-state-management-with-mobx.adoc
Labels: hilla, Language not checked

#2027 docs: update RTE value docs to reflect default format change (v24)
  .github/styles/Vocab/Docs/accept.txt
  articles/components/rich-text-editor/index.asciidoc
  frontend/demo/component/richtexteditor/rich-text-editor-set-get-value.ts
  src/main/java/com/vaadin/demo/component/richtexteditor/RichTextEditorSetGetValue.java
Labels: Language checked

#2112 Added a SSO Kit & Keycloak integration tutorial
  articles/tools/observability/integrations/datadog.asciidoc
  articles/tools/sso/integrations/images/keycloak-create-realm-button.png
  articles/tools/sso/integrations/index.asciidoc
  articles/tools/sso/integrations/keycloak.asciidoc
Labels: Language checked

#2160 fix: Deprecated LocalDateRenderer constructor
  articles/components/grid/flow.asciidoc
Labels: Language not checked

#2057 docs: added information on BrowserTestInfo
  articles/testing/end-to-end/advanced-concepts.adoc
Labels: Language checked

#2097 feat: add docs for NonNullApi and nullability annotation collision
  articles/lit/reference/type-nullability.adoc
Labels: hilla, Language checked

#2145 docs: update message list styling example
  articles/components/message-list/index.asciidoc
  frontend/demo/component/messages/message-list-with-theme-component.ts
  frontend/themes/docs/components/vaadin-message-with-theme.css
  frontend/themes/docs/components/vaadin-message.css
  frontend/themes/docs/message-list-theming.css
  frontend/themes/docs/styles.css
  src/main/java/com/vaadin/demo/component/messages/MessageListWithThemeComponent.java
Labels: Language checked

#2147 Reorganized production build chapter
  articles/lit/guides/production/production-build.asciidoc
Labels: Language checked

#2103 chore: update MPR docs for Vaadin 24
  articles/_vaadin-version.adoc
  articles/tools/mpr/configuration/mpr-cdi-tutorial.asciidoc
  articles/tools/mpr/configuration/session.asciidoc
  articles/tools/mpr/introduction/1-maven-v7.asciidoc
  articles/tools/mpr/introduction/1-maven-v8.asciidoc
  articles/tools/mpr/introduction/3-cdi.asciidoc
  articles/tools/mpr/introduction/3-spring-boot.asciidoc
  articles/upgrading/V23-V24-steps/index.adoc
  articles/upgrading/index.adoc
  scripts/version-update.sh
Labels: Language not checked

#2127 docs: remove mentions of polyfills and ES5 legacy stuff
  articles/advanced/i18n-localization.asciidoc
  articles/configuration/maven.asciidoc
  articles/configuration/properties.asciidoc
  articles/guide/start/gradle.asciidoc
  articles/integrations/embedding/exporter.asciidoc
  articles/production/production-build.adoc
  articles/production/troubleshooting.asciidoc
  articles/security/advanced-topics/frequent-issues.asciidoc
  articles/testing/end-to-end/installing-webdrivers.adoc
  articles/testing/end-to-end/multiple-browsers.adoc
  articles/testing/end-to-end/reliable-tests.adoc
Labels: Language checked

#2184 docs: improve Form Layout wording
  articles/components/form-layout/index.asciidoc
Labels: Language checked

#2134 docs: explain multiple fields in form layouts
  articles/components/form-layout/index.asciidoc
  frontend/demo/component/formlayout/form-layout-custom-field.ts
  src/main/java/com/vaadin/demo/component/formlayout/FormLayoutCustomField.java
Labels: Language checked

#2162 chore: replace PolymerTemplate with LitTemplate
  articles/tools/designer/using-designer/java.asciidoc
Labels: designer

#2149 Added a note about serialization
  articles/components/spreadsheet/index.asciidoc
Labels: Language checked

#2142 feat: remove Lit from React section
  articles/lit/guides/reactive-endpoints.adoc
  articles/lit/guides/security/configuring.adoc
  articles/lit/start/quick.adoc
Labels: hilla, Language checked

#2172 fix: remove using custom ui
  articles/integrations/cdi/instantiated-beans.asciidoc
Labels: flow

#2166 chore: remove VaadinWebSecurityConfigurerAdapter from examples
  articles/lit/guides/security/spring-login.adoc
  articles/lit/start/in-depth/login-and-authentication.adoc
  src/main/java/com/vaadin/demo/SecurityConfig.java
  src/main/java/com/vaadin/demo/fusion/security/authentication/SecurityConfigDemo.java
  src/main/java/com/vaadin/demo/fusion/security/stateless/SecurityConfig.java
Labels: hilla

#2161 feat: Add more example to the Shortcuts API chapter
  articles/create-ui/shortcut.asciidoc
Labels: flow, Language checked

#2187 docs: add Delta format details to RTE docs
  articles/components/rich-text-editor/index.asciidoc
Labels: Language checking

#2177 docs: add HTML format details to RTE docs
  articles/components/rich-text-editor/index.asciidoc
Labels: Language checked

#2183 docs: document using model properties in LitRenderer
  articles/components/grid/flow.asciidoc
Labels: Language checked

#2158 docs: add button icon tooltip example
  articles/components/button/index.asciidoc
  frontend/demo/component/button/button-icons.ts
  src/main/java/com/vaadin/demo/component/button/ButtonIcons.java
Labels: Language checked

#2146 Update and modernize the hotswapping instructions
  .github/styles/Vaadin/Terms-FrontendBackend.yml
  .github/styles/Vaadin/Terms.yml
  .github/styles/Vocab/Docs/accept.txt
  articles/configuration/live-reload/hotswap-agent.asciidoc
  articles/configuration/live-reload/index.asciidoc
Labels: Language checked

#2141 fix: update to clarify status of other JVM languages
  articles/lit/reference/endpoint-generator.adoc
  articles/lit/reference/feature-flags.adoc
  articles/lit/start/faq.adoc
Labels: hilla, Language checked

#2135 fix: Add notes on which order event handlers are called
  articles/routing/lifecycle.asciidoc
Labels: flow, Language checked

#2148 chore: updated Push documentation
  articles/advanced/server-push.asciidoc
  articles/tools/mpr/configuration/push.asciidoc
Labels: flow, Language checked

#2192 docs: add docs for spreadsheet custom components
  articles/components/spreadsheet/index.asciidoc
  frontend/demo/component/spreadsheet/spreadsheet-imports.ts
  src/main/java/com/vaadin/demo/component/spreadsheet/SpreadsheetComponents.java
Labels: Language checked

#2210 fix: update Spring Boot parent version
  pom.xml
Labels: hilla

#2207 docs: classic components absolute layout
  articles/advanced/classic-components.asciidoc
Labels: Language checked

#2211 feat: add multi-select combo box to multiple selection suggestions
  articles/lit/guides/forms/vaadin-components.asciidoc
Labels: Language checked

#2205 docs: add cell data section to Spreadsheet docs
  articles/components/spreadsheet/index.asciidoc
Labels: Language checked

#2200 docs: improve Flow grid sorting section
  articles/components/grid/flow.asciidoc
  articles/components/grid/index.asciidoc
Labels: Language checked

#2136 docs: ported and reworked Customizing System Messages documentation
  articles/advanced/customize-system-messages.adoc
Labels: flow, Language checked

#2140 chore: improved Vaadin session expiration docs
  articles/advanced/application-lifecycle.asciidoc
Labels: flow, Language checked

#2157 fix: update available properties
  articles/configuration/properties.asciidoc
Labels: flow, Language checked

#2159 docs: explain Custom Field value type and format
  articles/components/custom-field/index.asciidoc
Labels: Language checked

#2185 docs: add notes on distributed deployment
  articles/production/distributed-deployment.adoc
Labels: Language checked

#2191 docs: improve the description of pattern and allowedCharPattern
  articles/components/text-field/index.asciidoc
Labels: Language checked

#2195 feat: Document instantiator
  articles/advanced/custom-instantiators.asciidoc
Labels: flow, Language checked

#2196 chore: documented Spring add-on excludeUrls parameter
  articles/integrations/spring/configuration.asciidoc
Labels: flow, Language checked

#2203 docs: added notes on binding nested properties
  articles/binding-data/components-binder-beans.asciidoc
Labels: flow, Language checked

#2212 feat: explain the new `model` argument of `getFieldStrategy`
  articles/lit/guides/forms/web-component-field-strategy.asciidoc
  frontend/demo/fusion/forms/field-strategy/my-binder.ts
Labels: hilla, Language checked

#2202 docs: add Grid data provider examples
  articles/components/grid/index.asciidoc
  frontend/demo/component/grid/grid-data-provider.ts
  src/main/java/com/vaadin/demo/component/grid/GridDataProvider.java
  src/main/java/com/vaadin/demo/component/grid/PersonDataProvider.java
  src/main/java/com/vaadin/demo/component/grid/PersonFilter.java
Labels: Language checked

#2052 Hilla SSO Kit getting started
  articles/_commercial-banner.asciidoc
  articles/lit/acceleration-kits/index.adoc
  articles/lit/acceleration-kits/sso-kit/getting-started.adoc
  articles/lit/acceleration-kits/sso-kit/index.adoc
  articles/lit/acceleration-kits/sso-kit/theming.adoc
  articles/lit/index.adoc
  articles/react/acceleration-kits/index.adoc
  articles/react/acceleration-kits/sso-kit/getting-started.adoc
  articles/react/acceleration-kits/sso-kit/index.adoc
  articles/react/acceleration-kits/sso-kit/theming.adoc
  articles/react/index.adoc
  articles/react/reference/index.adoc
Labels: hilla, Language unchecked

#2221 Update React basics tutorial
  articles/lit/start/basics/index.adoc
Labels: hilla
