Repository vaadin/docs, pull requests merged in 2023-03, with the labels that each got.

#2236 chore : update Hilla branch to 2.0
  articles/lit/guides/endpoints.adoc
  articles/lit/guides/forms/binder-validation.asciidoc
  articles/lit/guides/forms/reference.adoc
  articles/lit/guides/security/spring-login.adoc
  articles/lit/reference/type-conversion.adoc
  articles/lit/reference/type-nullability.adoc
  articles/lit/start/basics/index.adoc
  articles/lit/start/in-depth/login-and-authentication.adoc
  dspublisher/dspublisher-scripts.js
  package-lock.json
  package.json
  pom.xml
  src/main/java/com/vaadin/demo/fusion/forms/dialogs/NewsletterSubscription.java
  src/main/java/com/vaadin/demo/fusion/forms/fieldstrategy/SamplePerson.java
  src/main/java/com/vaadin/demo/fusion/reactive/ReactiveEndpoint.java
  src/main/java/com/vaadin/demo/fusion/security/authentication/SecurityConfigDemo.java
  src/main/java/com/vaadin/demo/fusion/security/authentication/UserInfo.java
  src/main/java/com/vaadin/demo/fusion/security/authentication/UserInfoEndpoint.java
  src/main/java/com/vaadin/demo/fusion/security/stateless/SecurityConfig.java
  webpack.dspublisher.js
Labels: hilla

#2226 Docs: add upgrade notes for Hilla 2.0
  .github/styles/Vaadin/HeadingCase.yml
  articles/lit/guides/upgrading/_styling.adoc
  articles/lit/guides/upgrading/index.adoc
  articles/react/guides/upgrading/index.adoc
  src/main/java/com/vaadin/demo/fusion/security/stateless/SecurityConfig.java
Labels: hilla, Language unchecked

#2244 New Okta tutorial
  articles/tools/sso/integrations/okta.asciidoc
Labels: Language checked

#2270 Language and format updates for closed PR
  articles/production/docker.adoc
Labels: Language checked

#2284 One minor edit - PR2070
  articles/components/index.asciidoc
Labels: Language checked

#2279 Edited database-access & project-setup files.
  articles/tutorial/database-access.adoc
  articles/tutorial/project-setup.adoc
Labels: Language checked

#2280 Edited themes-for-embedded & utility-classes docs - PR2240
  articles/styling/advanced/themes-for-embedded.adoc
  articles/styling/lumo/utility-classes.adoc
Labels: Language checked

#2277 Edited all doc files touch in PR 1715
  articles/security/enabling-security.adoc
  articles/tools/index.asciidoc
  articles/tools/sso/getting-started.adoc
  articles/tools/sso/index.asciidoc
  articles/tools/sso/theming.asciidoc
Labels: Language checked

#2288 docs: use part name generator in grid styling demo
  articles/components/grid/index.asciidoc
  frontend/demo/component/grid/grid-styling.ts
  frontend/themes/docs/components/vaadin-grid-styling.css
  frontend/themes/docs/components/vaadin-grid.css
  frontend/themes/docs/grid-styling.css
  frontend/themes/docs/styles.css
  src/main/java/com/vaadin/demo/component/grid/GridStyling.java
Labels: Language checked

#2287 v24 tutorial updates
  articles/tutorial/components-and-layouts.adoc
  articles/tutorial/database-access.adoc
  articles/tutorial/e2e-testing-with-testbench.adoc
  articles/tutorial/forms-and-validation.adoc
  articles/tutorial/handling-view-state.adoc
  articles/tutorial/installing-and-offline-pwa.adoc
  articles/tutorial/login-and-authentication.adoc
  articles/tutorial/navigation-and-layouts.adoc
  articles/tutorial/project-setup.adoc
  articles/tutorial/unit-and-integration-testing.adoc
Labels: Language checking

#2283 Remove specific quota / pricing information
  articles/tools/collaboration/going-to-production.asciidoc
Labels: Language checked

#2290 add graalvm instructions
  .github/styles/Vocab/Docs/accept.txt
  articles/lit/guides/production/native.asciidoc
  articles/react/guides/production/native.asciidoc
Labels: hilla, Language checked

#2243 Clarifies embedded styling caveats
  articles/styling/custom-theme/creating-custom-theme.adoc
  articles/styling/lumo/utility-classes.adoc
Labels: Language checked

#2154 Docs: updated Creating a Java API for a Web Component
  articles/create-ui/web-components/index.asciidoc
  articles/create-ui/web-components/java-api-for-a-web-component.asciidoc
  src/main/java/com/vaadin/demo/ui/webcomponents/MwcSlider.java
Labels: Language checked

#2293 add instructions for installing graalvm
  articles/lit/guides/production/native.asciidoc
Labels: Language checked

#2294 Added Native Image Compilation instructions
  articles/production/native.asciidoc
Labels: Language checked

#2285 New Azure AD tutorial
  articles/tools/sso/integrations/azure-ad.asciidoc
  articles/tools/sso/integrations/keycloak.asciidoc
  articles/tools/sso/integrations/okta.asciidoc
Labels: Language checked

#2247 Update SSO Kit for Hilla getting started with the latest changes
  articles/lit/acceleration-kits/sso-kit/getting-started.adoc
Labels: hilla, Language checked

#2201 chore: improve resource loading documentation
  articles/advanced/loading-resources.asciidoc
Labels: flow, Language checked

#2317 More Editing of Lazy Data Binding Document
  articles/binding-data/data-provider.asciidoc
Labels: Language checked

#2320 Editing Kubernetes Debut Tool Document
  articles/tools/kubernetes/session-replication-debug-tool.adoc
Labels: Language checked

#2321 Edited Kubernetes Kit Index Page
  articles/tools/kubernetes/index.asciidoc
Labels: Language checked
