Repository vaadin/docs, pull requests merged in 2023-06, with the labels that each got.

#2464 Fix typo in SSO Azure tutorial
  articles/tools/sso/integrations/azure-ad.asciidoc
Labels: Language checked

#2462 docs: remove tree grid scroll to index warning
  articles/components/tree-grid/index.asciidoc
Labels: Language checked

#2452 Added docs for warning notification variant
  articles/components/notification/index.asciidoc
  articles/components/notification/styling.asciidoc
  frontend/demo/component/notification/notification-warning-preview.ts
  frontend/demo/component/notification/notification-warning.ts
  src/main/java/com/vaadin/demo/component/notification/NotificationWarning.java
Labels: Language checked

#2454 Docs/aria label apis
  articles/components/_input-field-common-features.adoc
  articles/components/_shared-code-snippets.adoc
  articles/components/checkbox/index.asciidoc
  articles/components/combo-box/index.asciidoc
  articles/components/date-picker/index.asciidoc
  articles/components/date-time-picker/index.asciidoc
  articles/components/email-field/index.asciidoc
  articles/components/number-field/index.asciidoc
  articles/components/password-field/index.asciidoc
  articles/components/radio-button/index.asciidoc
  articles/components/select/index.asciidoc
  articles/components/text-area/index.asciidoc
  articles/components/text-field/index.asciidoc
  articles/components/time-picker/index.asciidoc
  frontend/demo/component/datetimepicker/date-time-picker-internationalization.ts
  src/main/java/com/vaadin/demo/component/button/ButtonIcons.java
  src/main/java/com/vaadin/demo/component/button/ButtonLabels.java
  src/main/java/com/vaadin/demo/component/menubar/MenuBarIconOnly.java
  src/main/java/com/vaadin/demo/component/menubar/MenuBarIcons.java
  src/main/java/com/vaadin/demo/component/notification/NotificationLink.java
  src/main/java/com/vaadin/demo/component/notification/NotificationUndo.java
  src/main/java/com/vaadin/demo/component/splitlayout/SplitLayoutToggle.java
  src/main/java/com/vaadin/demo/component/tabs/TabSheetPrefixSuffix.java
Labels: Language checked

#2458 PR1949-Update Portlet setup documentation
  articles/integrations/portlet/adding-portlet-module.asciidoc
  articles/integrations/portlet/creating-multi-module-portlet-project.asciidoc
  articles/integrations/portlet/creating-vaadin-portlets.asciidoc
Labels: Language checking

#2436 feat: add article for Gradle support in Hilla
  .github/styles/Vocab/Docs/accept.txt
  articles/lit/start/gradle.adoc
  articles/react/start/gradle.adoc
Labels: hilla, Language checked

#2393 Observability V2.1 Release
  articles/tools/observability/configuration.asciidoc
  articles/tools/observability/customization.asciidoc
  articles/tools/observability/getting-started.asciidoc
  articles/tools/observability/index.asciidoc
  articles/tools/observability/reference.asciidoc
  pom.xml
  src/main/java/com/vaadin/demo/observability/UserBasedFrontendObservability.java
Labels: Language checked

#2459 PR1965 - Update Push Configuration Docs.
  articles/advanced/server-push.asciidoc
  articles/configuration/properties.asciidoc
Labels: Language checked

#2477 Recommend line-awesome add-on for V24
  articles/configuration/development-mode/index.asciidoc
  articles/upgrading/index.adoc
Labels: Language checked

#2483 docs: side nav component
  articles/components/index.asciidoc
  articles/components/side-nav/index.asciidoc
  articles/components/side-nav/side-nav.png
  articles/components/side-nav/styling.asciidoc
  frontend/demo/component/side-nav/side-nav-basic.ts
  frontend/demo/component/side-nav/side-nav-helper.ts
  frontend/demo/component/side-nav/side-nav-hierarchy.ts
  frontend/demo/component/side-nav/side-nav-labelled.ts
  frontend/demo/component/side-nav/side-nav-styling.ts
  frontend/demo/component/side-nav/side-nav-suffix.ts
  frontend/themes/docs/nav-item-styling.css
  frontend/themes/docs/styles.css
  src/main/java/com/vaadin/demo/component/sidenav/SideNavBasic.java
  src/main/java/com/vaadin/demo/component/sidenav/SideNavHierarchy.java
  src/main/java/com/vaadin/demo/component/sidenav/SideNavLabelled.java
  src/main/java/com/vaadin/demo/component/sidenav/SideNavStyling.java
  src/main/java/com/vaadin/demo/component/sidenav/SideNavSuffix.java
  src/main/java/com/vaadin/demo/component/sidenav/views/CalendarView.java
  src/main/java/com/vaadin/demo/component/sidenav/views/DashboardView.java
  src/main/java/com/vaadin/demo/component/sidenav/views/InboxView.java
  src/main/java/com/vaadin/demo/component/sidenav/views/MessagesView.java
  src/main/java/com/vaadin/demo/component/sidenav/views/PermissionsView.java
  src/main/java/com/vaadin/demo/component/sidenav/views/SentView.java
  src/main/java/com/vaadin/demo/component/sidenav/views/SettingsView.java
  src/main/java/com/vaadin/demo/component/sidenav/views/TrashView.java
  src/main/java/com/vaadin/demo/component/sidenav/views/UsersView.java
  src/main/resources/vaadin-featureflags.properties
Labels: Language checked

#2476 Add View Builder docs
  articles/_images/view-builder.svg
  articles/tools/index.asciidoc
  articles/tools/view-builder/images/view-builder-delete-button.png
  articles/tools/view-builder/images/view-builder-share.png
  articles/tools/view-builder/images/view-builder-start.png
  articles/tools/view-builder/images/view-with-components.png
  articles/tools/view-builder/index.asciidoc
Labels: Language checked

#2480 Clarify that Maven is supported
  articles/lit/start/gradle.adoc
Labels: Language checked

#2490 fix: use correct custom element for menu-bar icon examples
  frontend/demo/component/menubar/menu-bar-combo-buttons.ts
  frontend/demo/component/menubar/menu-bar-icon-only.ts
  frontend/demo/component/menubar/menu-bar-icons.ts
  frontend/demo/component/menubar/menu-bar-tooltip.ts
Labels: Language checked

#2489 Highlight new frontend o11y feature
  articles/tools/observability/index.asciidoc
Labels: Language unchecked

#2487 Minor Clean-Up: Tools - Azure Cloud
  articles/tools/azure-cloud/autoscaling.adoc
  articles/tools/azure-cloud/getting-started.adoc
  articles/tools/azure-cloud/index.asciidoc
  articles/tools/azure-cloud/multiple-kubernetes-environments.adoc
  articles/tools/azure-cloud/tls.adoc
Labels: Language checked

#2501 docs: Visual View Builder updates after going live
  articles/tools/theme-editor/index.asciidoc
  articles/tools/view-builder/images/view-builder-share.png
  articles/tools/view-builder/index.asciidoc
  package.json
Labels: Language checked

#2486 Add instructions for changing dark theme colors
  articles/styling/lumo/lumo-style-properties/color.adoc
  articles/styling/lumo/lumo-variants.adoc
Labels: Language checked

#2479 Update Hilla quick start tutorials
  articles/lit/start/quick.adoc
  articles/react/start/quick.adoc
Labels: hilla, Language checked

#2506 feat: setup react live examples
  README.md
  articles/components/accordion/index.asciidoc
  articles/components/app-layout/index.asciidoc
  articles/components/avatar/index.asciidoc
  articles/components/badge/index.asciidoc
  articles/components/button/index.asciidoc
  articles/components/combo-box/index.asciidoc
  articles/components/date-picker/index.asciidoc
  articles/components/grid/index.asciidoc
  articles/components/login/index.asciidoc
  articles/components/notification/index.asciidoc
  articles/components/tabs/index.asciidoc
  articles/components/upload/index.asciidoc
  dspublisher/config/production.json
  dspublisher/dspublisher-scripts.js
  frontend/demo/component/accordion/react/accordion-basic.tsx
  frontend/demo/component/app-layout/react/app-layout-basic.tsx
  frontend/demo/component/avatar/react/avatar-basic.tsx
  frontend/demo/component/badge/react/badge-basic.tsx
  frontend/demo/component/button/react/button-basic.tsx
  frontend/demo/component/combobox/react/combo-box-basic.tsx
  frontend/demo/component/grid/react/grid-basic.tsx
  frontend/demo/component/grid/react/grid-styling.tsx
  frontend/demo/component/login/react/login-basic.tsx
  frontend/demo/component/login/react/login-host-styles.ts
  frontend/demo/component/notification/react/notification-basic.tsx
  frontend/demo/react-example.ts
  package.json
  src/main/java/com/vaadin/dspublisher/licensecheck/Check.java
Labels: Language checked

#2274 Add Hilla SSO Kit Client documentation
  articles/lit/acceleration-kits/sso-kit/getting-started.adoc
  articles/lit/acceleration-kits/sso-kit/index.adoc
  articles/lit/acceleration-kits/sso-kit/theming.adoc
  articles/react/acceleration-kits/sso-kit/index.adoc
  articles/react/acceleration-kits/sso-kit/theming.adoc
Labels: hilla, Language checked

#2517 feat: add grid react examples
  articles/components/grid/index.asciidoc
  frontend/demo/component/grid/react/grid-column-reordering-resizing.tsx
  frontend/demo/component/grid/react/grid-content.tsx
  frontend/demo/component/grid/react/grid-lazy-column-rendering.tsx
Labels: Language checked

#2514 Minor Clean-Up: Tools - D to Kubernetes
  .github/styles/Vocab/Docs/accept.txt
  articles/tools/designer/getting-started/build-your-contact-form.asciidoc
  articles/tools/designer/getting-started/build-your-main-view.asciidoc
  articles/tools/designer/getting-started/connecting-your-contact-form-to-java.asciidoc
  articles/tools/designer/getting-started/connecting-your-main-view-to-java.asciidoc
  articles/tools/designer/getting-started/get-your-application-up-and-running.asciidoc
  articles/tools/designer/getting-started/setting-up-your-environment/_trial.asciidoc
  articles/tools/designer/getting-started/setting-up-your-environment/eclipse.asciidoc
  articles/tools/designer/getting-started/setting-up-your-environment/intellij.asciidoc
  articles/tools/designer/getting-started/wrap-up.asciidoc
  articles/tools/designer/index.asciidoc
  articles/tools/designer/using-designer/designing.asciidoc
  articles/tools/designer/using-designer/faq.asciidoc
  articles/tools/designer/using-designer/java.asciidoc
  articles/tools/designer/using-designer/layout.asciidoc
  articles/tools/designer/using-designer/previewing.asciidoc
  articles/tools/designer/using-designer/theming.asciidoc
  articles/tools/dspublisher/configuration.adoc
  articles/tools/dspublisher/custom-theme.adoc
  articles/tools/dspublisher/customization.adoc
  articles/tools/dspublisher/devmode.adoc
  articles/tools/dspublisher/editing.adoc
  articles/tools/dspublisher/index.adoc
  articles/tools/dspublisher/production.adoc
  articles/tools/dspublisher/start.adoc
  articles/tools/dspublisher/troubleshooting.adoc
  articles/tools/dspublisher/ui-examples.adoc
  articles/tools/dspublisher/updating.adoc
  articles/tools/kubernetes/_shared.adoc
  articles/tools/kubernetes/configuration.asciidoc
  articles/tools/kubernetes/getting-started.asciidoc
  articles/tools/kubernetes/index.asciidoc
  articles/tools/kubernetes/session-replication-debug-tool.adoc
  articles/tools/kubernetes/session-replication.adoc
  articles/tools/kubernetes/update-version.asciidoc
Labels: Language checked

#2522 Minor Clean-Up: Tools - MPR to Observability
  .github/styles/Vocab/Docs/accept.txt
  articles/tools/mpr/configuration/adding-legacy-components.asciidoc
  articles/tools/mpr/configuration/custom-ui.asciidoc
  articles/tools/mpr/configuration/index.asciidoc
  articles/tools/mpr/configuration/legacy-theme.asciidoc
  articles/tools/mpr/configuration/legacy-widgetset.asciidoc
  articles/tools/mpr/configuration/limitations.asciidoc
  articles/tools/mpr/configuration/mpr-cdi-tutorial.asciidoc
  articles/tools/mpr/configuration/production-mode.asciidoc
  articles/tools/mpr/configuration/push.asciidoc
  articles/tools/mpr/configuration/session.asciidoc
  articles/tools/mpr/index.asciidoc
  articles/tools/mpr/introduction/1-maven-v7.asciidoc
  articles/tools/mpr/introduction/1-maven-v8.asciidoc
  articles/tools/mpr/introduction/2-legacy-servlets.asciidoc
  articles/tools/mpr/introduction/3-cdi.asciidoc
  articles/tools/mpr/introduction/3-legacy-uis.asciidoc
  articles/tools/mpr/introduction/3-navigator.asciidoc
  articles/tools/mpr/introduction/3-no-framework.asciidoc
  articles/tools/mpr/introduction/3-spring-boot.asciidoc
  articles/tools/mpr/introduction/4-ui-parameters.asciidoc
  articles/tools/mpr/introduction/5-adding-legacy-components.asciidoc
  articles/tools/mpr/introduction/index.asciidoc
  articles/tools/mpr/overview.asciidoc
  articles/tools/observability/configuration.asciidoc
  articles/tools/observability/customization.asciidoc
  articles/tools/observability/getting-started.asciidoc
  articles/tools/observability/index.asciidoc
  articles/tools/observability/integrations/_run-app.asciidoc
  articles/tools/observability/integrations/datadog.asciidoc
  articles/tools/observability/integrations/grafana.asciidoc
  articles/tools/observability/integrations/index.asciidoc
  articles/tools/observability/integrations/jaeger-prometheus.asciidoc
  articles/tools/observability/integrations/newrelic.asciidoc
  articles/tools/observability/reference.asciidoc
Labels: Language checking

#2442 feat: WebPush tutorial
  .github/styles/Vocab/Docs/accept.txt
  articles/configuration/setting-up-webpush.adoc
Labels: Language checked
