Repository vaadin/docs, pull requests merged in 2023-11, with the labels that each got.

#2930 docs: add new input fields theming properties docs
  articles/components/_styling-section-theming-props.adoc
  articles/components/checkbox/styling.asciidoc
  articles/components/combo-box/styling.asciidoc
  articles/components/date-picker/styling.asciidoc
  articles/components/email-field/styling.asciidoc
  articles/components/multi-select-combo-box/styling.asciidoc
  articles/components/number-field/styling.asciidoc
  articles/components/password-field/styling.asciidoc
  articles/components/radio-button/styling.asciidoc
  articles/components/select/styling.asciidoc
  articles/components/text-area/styling.asciidoc
  articles/components/text-field/styling.asciidoc
  articles/components/time-picker/styling.asciidoc
Labels: Language checked

#2782 Feature/playwright testing
  articles/testing/index.adoc
  articles/testing/playwright.adoc
  articles/testing/selenium.adoc
Labels: Language checked

#2940 Add form change example
  articles/lit/guides/forms/form-status-tracking.adoc
  frontend/demo/fusion/forms/formchange/CompanyOfficeView.tsx
  src/main/java/com/vaadin/demo/fusion/forms/formchange/City.java
  src/main/java/com/vaadin/demo/fusion/forms/formchange/CompanyOffice.java
  src/main/java/com/vaadin/demo/fusion/forms/formchange/Country.java
  src/main/java/com/vaadin/demo/fusion/forms/formchange/OfficeService.java
  src/main/java/com/vaadin/demo/fusion/forms/formchange/package-info.java
Labels: Language checked

#2947 docs: recommend using a parent theme with dsp
  articles/tools/dspublisher/custom-theme.adoc
Labels: Language checked

#2954 docs: update click shortcut chapter in shortcut article
  articles/create-ui/shortcut.adoc
  articles/create-ui/shortcut.asciidoc
Labels: Language checked

#2956 docs: update articles for access denied error feature
  articles/routing/exceptions.asciidoc
  articles/security/advanced-topics/securing-plain-java-app.adoc
  articles/security/enabling-security.adoc
Labels: Language checked

#2948 docs: update article to describe new methods in ErrorEvent
  articles/advanced/custom-error-handler.asciidoc
Labels: Language checked

#2949 fix: Document acceptance of I18NProvider bean
  articles/advanced/i18n-localization.asciidoc
Labels: Language checked

#2951 docs: update production build article for prod bundle
  articles/production/production-build.adoc
Labels: Language checked

#2946 fix: Update dev bundle documentation
  articles/configuration/development-mode/index.asciidoc
Labels: Language checked

#2950 Update css-styling.asciidoc
  articles/components/charts/css-styling.asciidoc
Labels: Language checked

#2932 add auto form and auto crud component documentation
  .github/styles/Vaadin/ProductName.yml
  articles/react/components/auto-crud/index.asciidoc
  articles/react/components/auto-form/index.asciidoc
  articles/react/components/auto-grid/index.asciidoc
  frontend/demo/component/auto-crud/react/auto-crud-basic.tsx
  frontend/demo/component/auto-crud/react/auto-crud-customized-form.tsx
  frontend/demo/component/auto-crud/react/auto-crud-customized-grid.tsx
  frontend/demo/component/auto-form/react/auto-form-basic.tsx
  frontend/demo/component/auto-form/react/auto-form-custom-renderer-alt.tsx
  frontend/demo/component/auto-form/react/auto-form-custom-renderer.tsx
  frontend/demo/component/auto-form/react/auto-form-delete-after-delete.tsx
  frontend/demo/component/auto-form/react/auto-form-edit-new-modes.tsx
  frontend/demo/component/auto-form/react/auto-form-field-colspan.tsx
  frontend/demo/component/auto-form/react/auto-form-field-custom-label.tsx
  frontend/demo/component/auto-form/react/auto-form-field-custom-renderer.tsx
  frontend/demo/component/auto-form/react/auto-form-field-visibility.tsx
  frontend/demo/component/auto-form/react/auto-form-on-errors.tsx
  frontend/demo/component/auto-form/react/auto-form-responsive-steps.tsx
  frontend/demo/component/auto-grid/react/auto-grid-filtering.tsx
  frontend/demo/component/auto-grid/react/auto-grid-host-styles.ts
  frontend/demo/services/CrudService.ts
  frontend/demo/services/EmployeeService.ts
  frontend/demo/services/ProductService.ts
  frontend/demo/services/mocks.ts
  package-lock.json
  package.json
  pom.xml
  src/main/java/com/vaadin/demo/fusion/crud/Employee.java
  src/main/java/com/vaadin/demo/fusion/crud/EmployeeRepository.java
  src/main/java/com/vaadin/demo/fusion/crud/EmployeeService.java
Labels: Language checked

#2941 docs: add new Button theming CSS properties
  articles/components/button/styling.asciidoc
Labels: Language checked

#2973 docs: updated shortcut.adoc for resetFocusOnActiveElement
  articles/create-ui/shortcut.adoc
Labels: Language checked

#2963 docs: add examples for new MultiSelectComboBox features
  articles/components/multi-select-combo-box/index.asciidoc
  frontend/demo/component/multi-select-combo-box/multi-select-combo-box-auto-expand.ts
  frontend/demo/component/multi-select-combo-box/multi-select-combo-box-selected-items-on-top.ts
  frontend/demo/component/multi-select-combo-box/react/multi-select-combo-box-auto-expand.tsx
  frontend/demo/component/multi-select-combo-box/react/multi-select-combo-box-selected-items-on-top.tsx
  package-lock.json
  package.json
  src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxAutoExpand.java
  src/main/java/com/vaadin/demo/component/multiselectcombobox/MultiSelectComboBoxSelectedItemsOnTop.java
Labels: Language unchecked

#2987 Upgrade Hilla to 2.4.0
  package-lock.json
  package.json
  pom.xml
Labels: hilla

#3009 Reflect the refactoring of the start data classes
  articles/tutorial/components-and-layouts.adoc
  articles/tutorial/creating-a-component.adoc
  articles/tutorial/database-access.adoc
  articles/tutorial/handling-view-state.adoc
  articles/tutorial/images/setup/project-structure.png
  articles/tutorial/navigation-and-layouts.adoc
  articles/tutorial/unit-and-integration-testing.adoc
Labels: Language unchecked
