Repository vaadin/docs, pull requests merged in 2023-12, with the labels that each got.

#2989 cleanup of End-To-End testing part
  articles/tutorial/e2e-testing-with-testbench.adoc
Labels: Language checked

#3022 feat: add custom column order and grid refresh sections
  articles/react/components/auto-grid/index.asciidoc
  frontend/demo/component/auto-grid/react/auto-grid-custom-columns.tsx
Labels: Language checked

#3008 docs: implementing custom services for auto grid / form / crud
  articles/react/components/auto-crud/index.asciidoc
  articles/react/components/auto-form/index.asciidoc
  articles/react/components/auto-grid/index.asciidoc
  src/main/java/com/vaadin/demo/fusion/crud/ProductAdvancedDto.java
  src/main/java/com/vaadin/demo/fusion/crud/ProductAdvancedDtoListService.java
  src/main/java/com/vaadin/demo/fusion/crud/ProductDto.java
  src/main/java/com/vaadin/demo/fusion/crud/ProductDtoCrudService.java
  src/main/java/com/vaadin/demo/fusion/crud/ProductDtoListService.java
Labels: Language unchecked

#3023 docs: disable sorting and filtering in auto grid columns
  articles/react/components/auto-grid/index.asciidoc
  frontend/demo/component/auto-grid/react/auto-grid-no-header-filters.tsx
Labels: Language unchecked

#2937 Add further info in MenuBar best practices
  articles/components/menu-bar/index.adoc
Labels: Language checked

#2993 fix: Improve note about AppShellConfiguration
  articles/advanced/modifying-the-bootstrap-page.adoc
Labels: flow, Language checked

#3036 docs: use camel-case item properties in React example
  frontend/demo/component/combobox/react/combo-box-basic.tsx
Labels: Language unchecked

#3034 Docs/styling docs 243 update
  articles/components/_styling-section-theming-props.adoc
  articles/components/app-layout/styling.asciidoc
  articles/components/grid/styling.asciidoc
  articles/components/multi-select-combo-box/styling.adoc
  articles/components/rich-text-editor/styling.asciidoc
  articles/components/split-layout/index.asciidoc
  articles/components/tree-grid/styling.asciidoc
Labels: Language unchecked

#2995 Add a page for Collaboration Kit serialization
  articles/tools/collaboration/advanced/serialization.adoc
  articles/tools/kubernetes/session-replication.adoc
  src/main/java/com/vaadin/demo/collaboration/ConnectionContextExample.java
Labels: Language checked

#3039 feat: Explain React Router integration for Vaadin Flow
  articles/integrations/hilla.adoc
Labels: Language checked

#3046 docs: update MessageList docs to use CSS class
  articles/components/message-list/index.asciidoc
  frontend/demo/component/messages/message-list-with-theme-component.ts
  frontend/demo/component/messages/react/message-list-with-theme-component.tsx
  frontend/themes/docs/message-list-theming.css
  src/main/java/com/vaadin/demo/component/messages/MessageListWithThemeComponent.java
Labels: Language unchecked

#3043 docs: add ContextMenu className usage examples
  articles/components/context-menu/index.asciidoc
  frontend/demo/component/contextmenu/context-menu-classname.ts
  frontend/demo/component/contextmenu/react/context-menu-classname.tsx
  src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuClassname.java
Labels: Language unchecked

#3028 docs: clarify upload article regarding setAcceptedFileType
  articles/components/upload/index.asciidoc
Labels: Language checked

#3014 Update properties.asciidoc
  articles/configuration/properties.adoc
  articles/configuration/properties.asciidoc
Labels: flow, Language checked

#3051 Add link to hybrid example
  articles/integrations/hilla.adoc
Labels: Language checked

#3029 Add instructions for accessing authenticated user info
  articles/security/enabling-security.adoc
Labels: flow, Language checked

#3015 fix: Add a reference to rerouteToError annotation parameter
  articles/routing/exceptions.adoc
Labels: flow, Language checked

#3027 docs: auto form validation docs
  articles/react/components/auto-form/index.adoc
Labels: Language checked

#3070 Fix security articles
  articles/lit/guides/security/spring-login.adoc
  articles/lit/guides/security/spring-stateless.adoc
Labels: hilla

#3025 docs: custom service docs improvements
  articles/react/components/auto-crud/index.adoc
  articles/react/components/auto-crud/index.asciidoc
  articles/react/components/auto-form/index.adoc
  src/main/java/com/vaadin/demo/fusion/crud/ProductDtoFormService.java
  src/main/java/com/vaadin/demo/fusion/crud/ProductDtoListService.java
Labels: Language checked

#3073 Update AppSec Kit documentation for V8
  articles/appseckit/advanced-topics.asciidoc
  articles/appseckit/getting-started.asciidoc
Labels: Language checked

#3074 Update AppSec Kit documentation for V7
  articles/appseckit/advanced-topics.asciidoc
  articles/appseckit/getting-started.asciidoc
Labels: Language checked

#3048 docs: update MenuBar docs to use CSS class
  articles/components/menu-bar/index.adoc
  articles/components/message-list/index.adoc
  frontend/demo/component/menubar/menu-bar-custom-styling.ts
  frontend/demo/component/menubar/react/menu-bar-custom-styling.tsx
  frontend/themes/docs/menu-bar-theming.css
  frontend/themes/docs/styles.css
  src/main/java/com/vaadin/demo/component/menubar/MenuBarCustomStyling.java
Labels: Language checked

#3084 docs: remove use of Tabs in AppLayout examples
  frontend/demo/component/app-layout/app-layout-basic.ts
  frontend/demo/component/app-layout/app-layout-bottom-navbar.ts
  frontend/demo/component/app-layout/app-layout-drawer.ts
  frontend/demo/component/app-layout/app-layout-helper.ts
  frontend/demo/component/app-layout/app-layout-navbar-placement-side.ts
  frontend/demo/component/app-layout/app-layout-navbar-placement.ts
  frontend/demo/component/app-layout/app-layout-navbar.ts
  frontend/demo/component/app-layout/app-layout-secondary-navigation.ts
  frontend/demo/component/app-layout/react/app-layout-basic.tsx
  frontend/demo/component/app-layout/react/app-layout-bottom-navbar.tsx
  frontend/demo/component/app-layout/react/app-layout-drawer.tsx
  frontend/demo/component/app-layout/react/app-layout-navbar-placement-side.tsx
  frontend/demo/component/app-layout/react/app-layout-navbar-placement.tsx
  frontend/demo/component/app-layout/react/app-layout-navbar.tsx
  frontend/demo/component/app-layout/react/app-layout-secondary-navigation.tsx
  frontend/themes/docs/theme.json
  src/main/java/com/vaadin/demo/component/applayout/AppLayoutBasic.java
  src/main/java/com/vaadin/demo/component/applayout/AppLayoutBottomNavbar.java
  src/main/java/com/vaadin/demo/component/applayout/AppLayoutDrawer.java
  src/main/java/com/vaadin/demo/component/applayout/AppLayoutNavbar.java
  src/main/java/com/vaadin/demo/component/applayout/AppLayoutNavbarPlacement.java
  src/main/java/com/vaadin/demo/component/applayout/AppLayoutNavbarPlacementSide.java
  src/main/java/com/vaadin/demo/component/applayout/AppLayoutSecondaryNavigation.java
Labels: Language unchecked

#3092 docs: swap logout instructions
  articles/security/advanced-topics/securing-plain-java-app.adoc
  articles/tools/mpr/configuration/session.asciidoc
Labels: flow
