Repository vaadin/docs, pull requests merged in 2023-10, with the labels that each got.

#2857 Fix internal link in AppSec Kit documentation
  articles/tools/appsec/advanced-topics.asciidoc
  articles/tools/appsec/getting-started.asciidoc
  pom.xml
Labels: Language checked

#2836 docs: add AutoGrid article
  articles/react/components/auto-grid/index.asciidoc
  articles/react/components/index.asciidoc
  frontend/demo/component/auto-grid/react/auto-grid-basic.tsx
  frontend/demo/component/auto-grid/react/auto-grid-filtering.tsx
  frontend/demo/component/auto-grid/react/auto-grid-host-styles.ts
  frontend/demo/component/auto-grid/react/auto-grid-no-header-filters.tsx
  frontend/demo/component/auto-grid/react/auto-grid-selection.tsx
  frontend/demo/component/auto-grid/react/auto-grid-visible-columns.tsx
  frontend/demo/fusion/forms/field-strategy/my-binder.ts
  frontend/themes/docs/theme-editor.css
  package-lock.json
  package.json
  pom.xml
  src/main/java/com/vaadin/demo/fusion/crud/Product.java
  src/main/java/com/vaadin/demo/fusion/crud/ProductRepository.java
  src/main/java/com/vaadin/demo/fusion/crud/ProductService.java
  src/main/resources/application.properties
  src/main/resources/data.sql
Labels: hilla, Language checked

#2815 Update Collaboration Kit licensing details
  articles/tools/collaboration/developing-with-ce.asciidoc
Labels: Language checked

#2846 docs: add note about proxy configuration credential
  articles/configuration/development-mode/node-js.asciidoc
Labels: Language checked

#2845 docs: add auto grid guide
  articles/react/guides/data-grids.adoc
  src/main/java/com/vaadin/demo/DownloadController.java
  src/main/resources/files/product-data.sql
Labels: Language checked

#2871 feat: add note about visibleColumns and sensitive data
  articles/react/components/auto-grid/index.asciidoc
Labels: Language checked

#2873 docs: update Auto Grid article and warn about experimentalFilter
  articles/react/components/auto-grid/index.asciidoc
  frontend/demo/component/auto-grid/react/auto-grid-filtering.tsx
  package-lock.json
  package.json
  pom.xml
Labels: hilla, Language unchecked

#2872 docs: auto-grid column options
  articles/react/components/auto-grid/index.asciidoc
  frontend/demo/component/auto-grid/react/auto-grid-column-options.tsx
Labels: Language checked

#2874 chore: Add an experimental disclaimer to Web Push
  articles/configuration/setting-up-webpush.adoc
Labels: Language checked

#2795 Minor Clean-Up: guide to integration
  .github/styles/Vaadin/Abbr.yml
  .github/styles/Vaadin/So.yml
  articles/guide/quick-start.adoc
  articles/guide/start/gradle.asciidoc
  articles/guide/start/index.asciidoc
  articles/guide/start/maven-archetype.asciidoc
  articles/guide/step-by-step/importing/eclipse.asciidoc
  articles/guide/step-by-step/importing/index.asciidoc
  articles/guide/step-by-step/importing/intellij.asciidoc
  articles/guide/step-by-step/importing/netbeans.asciidoc
  articles/guide/step-by-step/importing/vscode.asciidoc
  articles/guide/step-by-step/running/eclipse.asciidoc
  articles/guide/step-by-step/running/index.asciidoc
  articles/guide/step-by-step/running/intellij.asciidoc
  articles/guide/step-by-step/running/netbeans.asciidoc
  articles/integrations/cdi/contexts.asciidoc
  articles/integrations/cdi/events.asciidoc
  articles/integrations/cdi/index.asciidoc
  articles/integrations/cdi/instantiated-beans.asciidoc
  articles/integrations/databases/_shared.adoc
  articles/integrations/databases/mariadb.adoc
  articles/integrations/databases/mysql.adoc
  articles/integrations/databases/postgresql.adoc
  articles/integrations/embedding/exporter.asciidoc
  articles/integrations/embedding/index.asciidoc
  articles/integrations/embedding/limitations.asciidoc
  articles/integrations/embedding/preserveonrefresh.asciidoc
  articles/integrations/embedding/properties.asciidoc
  articles/integrations/embedding/push.asciidoc
  articles/integrations/embedding/security.asciidoc
  articles/integrations/embedding/theming.asciidoc
  articles/integrations/osgi/advanced.asciidoc
  articles/integrations/osgi/index.asciidoc
  articles/integrations/osgi/karaf.asciidoc
  articles/integrations/portlet/adding-portlet-module.asciidoc
  articles/integrations/spring/index.asciidoc
  articles/integrations/spring/routing.asciidoc
  articles/integrations/spring/scopes.asciidoc
  articles/integrations/spring/spring-boot.asciidoc
  articles/integrations/spring/spring-mvc.asciidoc
Labels: Language checked

#2883 fix: add examples of customColumns and accessing sub properties
  articles/react/components/auto-grid/index.asciidoc
  frontend/demo/component/auto-grid/react/auto-grid-custom-columns.tsx
  frontend/demo/component/auto-grid/react/auto-grid-visible-columns.tsx
  src/main/java/com/vaadin/demo/fusion/crud/Product.java
  src/main/java/com/vaadin/demo/fusion/crud/ProductService.java
  src/main/java/com/vaadin/demo/fusion/crud/Supplier.java
  src/main/resources/data.sql
Labels: Language checked

#2890 Docs/styling docs fixes
  articles/components/combo-box/styling.asciidoc
  articles/components/date-picker/styling.asciidoc
  articles/components/email-field/styling.asciidoc
  articles/components/multi-select-combo-box/styling.asciidoc
  articles/components/number-field/styling.asciidoc
  articles/components/password-field/styling.asciidoc
  articles/components/select/styling.asciidoc
  articles/components/side-nav/styling.asciidoc
Labels: Language unchecked

#2869 Updated Hilla React tutorial
  articles/react/start/basics/images/basics-project-structure.png
  articles/react/start/basics/images/basics-running-1.png
  articles/react/start/basics/images/basics-running-2.png
  articles/react/start/basics/images/list-and-form.png
  articles/react/start/basics/index.adoc
Labels: Language checked

#2856 Add Spring Security article for React
  articles/lit/guides/security/role-based-access.adoc
  articles/lit/guides/security/spring-login.adoc
  articles/react/guides/security/spring-login.adoc
  frontend/demo/auth/AboutView.tsx
  frontend/demo/auth/App.tsx
  frontend/demo/auth/LoginView.tsx
  frontend/demo/auth/MainLayout.tsx
  frontend/demo/auth/auth.ts
  frontend/demo/auth/routes.tsx
  frontend/demo/auth/routing.ts
  frontend/demo/fusion/authentication/auth.ts
  frontend/demo/fusion/forms/contact-form.ts
  src/main/java/com/vaadin/demo/fusion/security/authentication/SecurityConfigDemo.java
  src/main/java/com/vaadin/demo/fusion/security/authentication/UserInfoService.java
Labels: Language checked

#2887 Improve PreserveOnRefresh documentation
  articles/flow/advanced/tutorial-preserving-state-on-refresh.asciidoc
  articles/flow/integrations/cdi/tutorial-cdi-contexts.asciidoc
  articles/flow/upgrading/v8/3-general-differences.asciidoc
Labels: Language checked

#2902 Improve CDI PreserveOnRefresh documentation
  articles/integrations/cdi/contexts.asciidoc
Labels: Language checked

#2896 docs: note about eagerServerLoad property in exceptions article
  articles/routing/exceptions.asciidoc
Labels: Language checked

#2912 chore: Hide OSGi integration as it's not supported in V24
  articles/integrations/osgi/advanced.asciidoc
  articles/integrations/osgi/index.asciidoc
  articles/integrations/osgi/karaf.asciidoc
Labels: Language checked

#2908 Add note of changed getPathInfo behavior and implications on cookies
  articles/upgrading/essential-steps/instructions/_common.adoc
Labels: Language checked

#2927 Add link to source code
  .github/styles/Vaadin/Abbr.yml
  articles/react/start/basics/index.adoc
Labels: Language checked
