Repository vaadin/docs, pull requests merged in 2024-07, with the labels that each got.

#3372 The Vaadin Way Architecture
  .github/styles/Vaadin/Abbr.yml
  articles/building-apps/architecture/components.adoc
  articles/building-apps/architecture/design.adoc
  articles/building-apps/architecture/images/c4-component.png
  articles/building-apps/architecture/images/c4-container-simplified.png
  articles/building-apps/architecture/images/c4-container.png
  articles/building-apps/architecture/images/c4-context.png
  articles/building-apps/architecture/images/combined-spi-api.png
  articles/building-apps/architecture/images/components-with-spi.png
  articles/building-apps/architecture/images/layers.png
  articles/building-apps/architecture/images/microservices-aggregating.png
  articles/building-apps/architecture/images/microservices-dedicated.png
  articles/building-apps/architecture/images/three-components.png
  articles/building-apps/architecture/index.adoc
  articles/building-apps/architecture/layers.adoc
  articles/building-apps/architecture/microservices.adoc
  articles/building-apps/architecture/monoliths.adoc
  articles/building-apps/index.adoc
Labels: Language checking

#3518 fix: fix react opt-out note
  articles/upgrading/index.adoc
Labels: flow, Language checked

#3420 Create category for Control Center
  .github/styles/Vaadin/Abbr.yml
  articles/control-center/getting-started/index.adoc
  articles/control-center/index.adoc
  articles/control-center/overview/index.adoc
Labels: Language checked

#3493 docs: add grid empty state documentation
  articles/components/grid/index.adoc
  frontend/demo/component/grid/grid-empty-state.ts
  frontend/demo/component/grid/react/grid-empty-state.tsx
  src/main/java/com/vaadin/demo/component/grid/GridEmptyState.java
Labels: Language checked

#3523 Control Center startup configuration wizard
  .github/styles/config/vocabularies/Docs/accept.txt
  articles/control-center/getting-started/images/configure-hostnames.png
  articles/control-center/getting-started/images/finalizing-setup.png
  articles/control-center/getting-started/images/keycloak-realm.png
  articles/control-center/getting-started/images/welcome.png
  articles/control-center/getting-started/startup-configuration.adoc
Labels: Language checked

#3561 docs: add MenuBar dropdown indicators theme variant example
  articles/components/menu-bar/index.adoc
  frontend/demo/component/menubar/menu-bar-drop-down-indicators.ts
  frontend/demo/component/menubar/react/menu-bar-drop-down-indicators.tsx
  src/main/java/com/vaadin/demo/component/menubar/MenuBarDropDownIndicators.java
Labels: Language unchecked

#3564 docs: add example for Button warning theme variant
  articles/components/button/index.adoc
  frontend/demo/component/button/button-warning.ts
  frontend/demo/component/button/react/button-warning.tsx
  src/main/java/com/vaadin/demo/component/button/ButtonWarning.java
Labels: Language unchecked
