Repository vaadin/docs, pull requests merged in 2024-08, with the labels that each got.

#3575 fix: fix connect client prefix property name (#3128) (CP: latest)
  articles/hilla/lit/guides/client-middleware.adoc
Labels: hilla

#3572 chore: fix spring login example code
  articles/hilla/lit/guides/security/spring-login.adoc
Labels: hilla

#3488 feat: add documentation for Flow in React
  articles/flow/integrations/react.adoc
Labels: Language checked

#3583 add control-center user management docs
  articles/control-center/user-management/images/2fa.png
  articles/control-center/user-management/images/create_role.png
  articles/control-center/user-management/images/create_user.png
  articles/control-center/user-management/images/create_user_group.png
  articles/control-center/user-management/images/manage_user.png
  articles/control-center/user-management/images/reset_password.png
  articles/control-center/user-management/images/roles.png
  articles/control-center/user-management/images/user_groups.png
  articles/control-center/user-management/images/user_management_1.png
  articles/control-center/user-management/images/user_management_enabled.png
  articles/control-center/user-management/images/user_management_user_selected.png
  articles/control-center/user-management/index.adoc
Labels: Language checked

#3589 Remove step no longer needed to deploy Vaadin app to Control Center
  articles/control-center/application-discovery/index.adoc
Labels: Language checked

#3578 docs: document DnD related part names
  articles/components/grid/styling.adoc
Labels: Language checked

#3600 Document how to wrap a field React component into Flow component
  articles/flow/integrations/react.adoc
Labels: Language unchecked

#3577 chore: add a note about Unremovable annotation for Quarkus beans
  articles/flow/integrations/quarkus.adoc
Labels: flow, Language checked

#3602 Add strict csp instructions
  .github/styles/Vaadin/Abbr.yml
  articles/flow/security/advanced-topics/strict-csp.adoc
Labels: Language checked

#3626 docs: update source group names
  articles/components/button/index.adoc
  articles/components/dialog/index.adoc
  articles/components/upload/file-handling.adoc
Labels: Language unchecked

#3616 mtk docs (#3615)
  .github/styles/Vaadin/Abbr.yml
  .github/styles/config/vocabularies/Docs/accept.txt
  articles/tools/modernization-toolkit/analyzer-for-eclipse.adoc
  articles/tools/modernization-toolkit/analyzer-for-maven.adoc
  articles/tools/modernization-toolkit/classic-components.adoc
  articles/tools/modernization-toolkit/dragonfly.adoc
  articles/tools/modernization-toolkit/feature-pack.adoc
  articles/tools/modernization-toolkit/index.adoc
Labels: Language checked

#3631 Wrap Field React Component into Flow Component - PR 3600
  articles/flow/integrations/react.adoc
Labels: Language checked
