Repository vaadin/docs, pull requests merged in 2024-10, with the labels that each got.

#3608 docs: control center localization feature
  articles/control-center/localization/images/add-language.png
  articles/control-center/localization/images/editing-translations.png
  articles/control-center/localization/images/feature-toggle.png
  articles/control-center/localization/images/upload-dialog.png
  articles/control-center/localization/index.adoc
Labels: Language checked

#3768 chore: remove extra .png from the screenshot file name
  articles/getting-started/tutorial/hilla/images/lobby_view_with_channels.png
  articles/getting-started/tutorial/hilla/second-view.adoc
Labels: Language unchecked

#3771 chore: align order for tools section subfolders
  articles/tools/ai-form-filler/index.adoc
  articles/tools/appsec/index.adoc
  articles/tools/azure-cloud/index.adoc
  articles/tools/collaboration/index.adoc
  articles/tools/copilot/index.adoc
  articles/tools/designer/index.adoc
  articles/tools/dspublisher/index.adoc
  articles/tools/kubernetes/index.adoc
  articles/tools/modernization-toolkit/index.adoc
  articles/tools/mpr/index.adoc
  articles/tools/observability/index.adoc
  articles/tools/sso/index.adoc
  articles/tools/start/index.adoc
  articles/tools/swing/index.adoc
Labels: Language unchecked

#3735 fix: Add a note about Grid's refresh behavior
  articles/flow/binding-data/data-provider.adoc
Labels: Language unchecked

#3772 chore: add missing order to Tutorial page
  articles/getting-started/tutorial/index.adoc
Labels: Language unchecked

#3773 docs: fix cross-references in Control Center docs
  articles/control-center/dev-mode/index.adoc
Labels: Language unchecked

#3802 fix: Add note that UI Unit Test does not support Java EE based applications
  articles/flow/testing/ui-unit/index.adoc
Labels: Language unchecked

#3775 Copilot i18n docs
  articles/tools/copilot/i18n.adoc
  articles/tools/copilot/index.adoc
Labels: Language checked

#3816 chore: fix some typos, remove trailing whitespaces
  articles/building-apps/application-layer/application-services.adoc
  articles/building-apps/application-layer/persistence/repositories/index.adoc
  articles/building-apps/application-layer/persistence/repositories/pluggable.adoc
  articles/building-apps/architecture/monoliths.adoc
  articles/components/notification/styling.adoc
  articles/flow/advanced/custom-instantiators.adoc
  articles/flow/create-ui/shortcut.adoc
  articles/flow/testing/end-to-end/advanced-concepts.adoc
  articles/flow/tutorial/project-setup.adoc
  articles/upgrading/index.adoc
Labels: Language unchecked

#3764 Update RTE image support documentation
  articles/components/rich-text-editor/index.adoc
Labels: Language checked

#3759 Background jobs
  .github/workflows/vale.yml
  articles/building-apps/application-layer/background-jobs/images/job-and-triggers.png
  articles/building-apps/application-layer/background-jobs/index.adoc
  articles/building-apps/application-layer/background-jobs/interaction/callbacks.adoc
  articles/building-apps/application-layer/background-jobs/interaction/futures.adoc
  articles/building-apps/application-layer/background-jobs/interaction/index.adoc
  articles/building-apps/application-layer/background-jobs/interaction/reactive.adoc
  articles/building-apps/application-layer/background-jobs/jobs.adoc
  articles/building-apps/application-layer/background-jobs/triggers.adoc
  articles/building-apps/application-layer/domain-primitives.adoc
  articles/building-apps/application-layer/persistence/index.adoc
  articles/building-apps/index.adoc
  articles/building-apps/presentation-layer/index.adoc
  articles/building-apps/presentation-layer/server-push/callbacks.adoc
  articles/building-apps/presentation-layer/server-push/futures.adoc
  articles/building-apps/presentation-layer/server-push/index.adoc
  articles/building-apps/presentation-layer/server-push/reactive-browser-callable-services.adoc
  articles/building-apps/presentation-layer/server-push/reactive.adoc
  articles/building-apps/presentation-layer/server-push/threads.adoc
  articles/building-apps/presentation-layer/server-push/updates.adoc
  articles/flow/advanced/long-running-tasks.adoc
  articles/flow/advanced/server-push.adoc
  articles/hilla/lit/guides/reactive-endpoints.adoc
Labels: Language checked, the vaadin way

#3827 Fix typos
  articles/building-apps/application-layer/background-jobs/jobs.adoc
  articles/building-apps/application-layer/background-jobs/triggers.adoc
Labels: Language unchecked

#3797 feat: add initial Full-stack Signals documentation
  articles/hilla/guides/full-stack-signals.adoc
Labels: Language checked

#3823 fix: correct to more precise explanation about binder error handling
  articles/hilla/lit/guides/forms/binder-load.adoc
Labels: Language checked

#3833 Suggest to use a proper tag for app images
  articles/control-center/application-deployment/index.adoc
Labels: Language checked

#3840 docs: fix broken cross-references in Classic Components
  articles/tools/modernization-toolkit/classic-components.adoc
Labels: Language unchecked

#3754 Document how to deploy Control Center with a custom ingress
  articles/control-center/getting-started/index.adoc
  articles/control-center/identity-management/index.adoc
Labels: Language checked

#3851 Remove Control Center production use admonition
  articles/control-center/index.adoc
Labels: Language unchecked

#3843 Persistence take two
  .github/styles/Vaadin/Abbr.yml
  articles/building-apps/application-layer/application-services.adoc
  articles/building-apps/application-layer/background-jobs/jobs.adoc
  articles/building-apps/application-layer/consistency/eventual.adoc
  articles/building-apps/application-layer/consistency/index.adoc
  articles/building-apps/application-layer/consistency/optimistic-locking.adoc
  articles/building-apps/application-layer/consistency/pessimistic-locking.adoc
  articles/building-apps/application-layer/consistency/strong.adoc
  articles/building-apps/application-layer/consistency/transactions/declarative.adoc
  articles/building-apps/application-layer/consistency/transactions/images/declarative-transactions-self-call.png
  articles/building-apps/application-layer/consistency/transactions/images/declarative-transactions.png
  articles/building-apps/application-layer/consistency/transactions/index.adoc
  articles/building-apps/application-layer/consistency/transactions/programmatic.adoc
  articles/building-apps/application-layer/consistency/validation.adoc
  articles/building-apps/application-layer/domain-primitives.adoc
  articles/building-apps/application-layer/persistence/repositories/index.adoc
  articles/building-apps/application-layer/persistence/repositories/jooq.adoc
  articles/building-apps/application-layer/persistence/repositories/jpa.adoc
  articles/building-apps/application-layer/persistence/repositories/pluggable.adoc
Labels: Language checked, the vaadin way

#3815 Introduction to UX
  articles/building-apps/presentation-layer/design/index.adoc
  articles/building-apps/presentation-layer/design/visuals/color.adoc
  articles/building-apps/presentation-layer/design/visuals/images/color-contrast.png
  articles/building-apps/presentation-layer/design/visuals/images/color-palette.png
  articles/building-apps/presentation-layer/design/visuals/images/color-shapes1.png
  articles/building-apps/presentation-layer/design/visuals/images/color-shapes2.png
  articles/building-apps/presentation-layer/design/visuals/images/color-ui-example.png
  articles/building-apps/presentation-layer/design/visuals/images/sizing.png
  articles/building-apps/presentation-layer/design/visuals/images/spacing.png
  articles/building-apps/presentation-layer/design/visuals/images/typography-font-size.png
  articles/building-apps/presentation-layer/design/visuals/images/typography-monospace-css.png
  articles/building-apps/presentation-layer/design/visuals/images/typography-monospace.png
  articles/building-apps/presentation-layer/design/visuals/images/typography-serif-sans-serif.png
  articles/building-apps/presentation-layer/design/visuals/images/typography-type-scale.png
  articles/building-apps/presentation-layer/design/visuals/index.adoc
  articles/building-apps/presentation-layer/design/visuals/size-space.adoc
  articles/building-apps/presentation-layer/design/visuals/typography.adoc
Labels: Language checked, the vaadin way

#3862 [Control Center] Add a section about displaying buttons based on authentication status
  articles/control-center/identity-management/index.adoc
  articles/control-center/identity-management/login-logout.adoc
Labels: Language checked

#3864 Images enhanced and typos corrected
  .github/styles/config/vocabularies/Docs/accept.txt
  articles/building-apps/presentation-layer/design/visuals/color.adoc
  articles/building-apps/presentation-layer/design/visuals/images/color-contrast-chrome.png
  articles/building-apps/presentation-layer/design/visuals/images/color-contrast.png
  articles/building-apps/presentation-layer/design/visuals/images/color-shapes1.png
  articles/building-apps/presentation-layer/design/visuals/images/color-shapes2.png
  articles/building-apps/presentation-layer/design/visuals/images/color-ui-example.png
  articles/building-apps/presentation-layer/design/visuals/images/sizing.png
  articles/building-apps/presentation-layer/design/visuals/images/spacing.png
  articles/building-apps/presentation-layer/design/visuals/images/typography-font-size.png
  articles/building-apps/presentation-layer/design/visuals/images/typography-monospace-css.png
  articles/building-apps/presentation-layer/design/visuals/images/typography-monospace.png
  articles/building-apps/presentation-layer/design/visuals/images/typography-serif-sans-serif.png
  articles/building-apps/presentation-layer/design/visuals/images/typography-type-scale.png
  articles/building-apps/presentation-layer/design/visuals/size-space.adoc
  articles/building-apps/presentation-layer/design/visuals/typography.adoc
Labels: Language checked
