Repository vaadin/docs, pull requests merged in 2024-09, with the labels that each got.

#3618 feat: Document @Layout
  articles/flow/integrations/hilla.adoc
  articles/flow/routing/layout.adoc
Labels: Language checked

#3630 Flow Description - PR 3465
  articles/flow/what-is-flow.adoc
Labels: Language checked

#3638 fix: escape special chars correctly in pattern
  frontend/demo/component/custom-field/react/custom-field-native-input.tsx
  frontend/demo/component/textfield/react/text-field-constraints.tsx
  frontend/demo/component/textfield/text-field-constraints.ts
  src/main/java/com/vaadin/demo/component/textfield/TextFieldConstraints.java
Labels: Language unchecked

#3639 docs: add missing button and progress-bar variants
  articles/components/button/styling.adoc
  articles/components/progress-bar/styling.adoc
Labels: Language unchecked

#3642 fix: use correct npm packages for basic layouts links
  articles/components/basic-layouts/index.adoc
  articles/components/horizontal-layout/index.adoc
  articles/components/vertical-layout/index.adoc
Labels: Language unchecked

#3644 docs: add since tag to popover description
  articles/components/popover/index.adoc
Labels: Language unchecked

#3649 docs: remove mentions of deleted webpackTemplate
  articles/hilla/guides/production/production-build.adoc
  articles/hilla/lit/guides/production/production-build.adoc
Labels: Language unchecked

#3643 chore: fix some typos detected by cspell
  articles/contributing/docs/vale.adoc
  articles/flow/security/advanced-topics/navigation-access-control.adoc
  articles/getting-started/tutorial/flow/layout.adoc
  articles/getting-started/tutorial/flow/styling.adoc
  articles/getting-started/tutorial/hilla/first-view.adoc
  articles/getting-started/tutorial/hilla/layout.adoc
  articles/tools/collaboration/advanced/backend-api.adoc
  articles/tools/kubernetes/getting-started.adoc
  articles/tools/kubernetes/update-version.adoc
  articles/tools/swing/communication.adoc
  src/main/java/com/vaadin/demo/component/notification/NotificationRetry.java
Labels: Language unchecked

#3624 Documentation for Html Component
  articles/flow/create-ui/standard-html.adoc
Labels: Language checked

#3620 Project structure
  .github/styles/Vaadin/Abbr.yml
  articles/building-apps/project-structure/images/services-api.png
  articles/building-apps/project-structure/images/spi.png
  articles/building-apps/project-structure/index.adoc
  articles/building-apps/project-structure/multi-module.adoc
  articles/building-apps/project-structure/single-module.adoc
  articles/building-apps/spring-boot.adoc
Labels: Language checked, the vaadin way

#3646 Domain primitives
  articles/building-apps/application-layer/domain-primitives.adoc
  articles/building-apps/application-layer/index.adoc
Labels: Language checked, the vaadin way

#3668 Add article for Control Center Development Mode
  .github/styles/config/vocabularies/Docs/accept.txt
  articles/control-center/dev-mode/index.adoc
Labels: Language checked, control-center

#3669 Improve and restructure Control Center articles
  .github/styles/Vaadin/Abbr.yml
  .github/styles/config/vocabularies/Docs/accept.txt
  articles/control-center/application-deployment/hostname-guidelines.adoc
  articles/control-center/application-deployment/images/app-deploy.png
  articles/control-center/application-deployment/images/app-selector.png
  articles/control-center/application-deployment/index.adoc
  articles/control-center/application-discovery/images/deploy_button.png
  articles/control-center/application-discovery/images/deploy_dialog_1.png
  articles/control-center/application-discovery/images/orphaned.png
  articles/control-center/application-discovery/images/scale_dialog.png
  articles/control-center/application-discovery/index.adoc
  articles/control-center/getting-started/images/configure-hostnames.png
  articles/control-center/getting-started/images/dashboard-view.png
  articles/control-center/getting-started/images/finalizing-setup.png
  articles/control-center/getting-started/images/hostname-step.png
  articles/control-center/getting-started/images/install-step.png
  articles/control-center/getting-started/images/keycloak-realm.png
  articles/control-center/getting-started/images/login-view.png
  articles/control-center/getting-started/images/user-step.png
  articles/control-center/getting-started/images/welcome-step.png
  articles/control-center/getting-started/images/welcome.png
  articles/control-center/getting-started/index.adoc
  articles/control-center/getting-started/startup-configuration.adoc
  articles/control-center/identity-management/images/app-dashboard.png
  articles/control-center/identity-management/images/group-create.png
  articles/control-center/identity-management/images/role-create.png
  articles/control-center/identity-management/images/user-create.png
  articles/control-center/identity-management/images/user-detail.png
  articles/control-center/identity-management/index.adoc
  articles/control-center/index.adoc
  articles/control-center/overview/index.adoc
  articles/control-center/user-management/images/2fa.png
  articles/control-center/user-management/images/create_role.png
  articles/control-center/user-management/images/create_user.png
  articles/control-center/user-management/images/create_user_group.png
  articles/control-center/user-management/images/manage_user.png
  articles/control-center/user-management/images/reset_password.png
  articles/control-center/user-management/images/roles.png
  articles/control-center/user-management/images/user_groups.png
  articles/control-center/user-management/images/user_management_1.png
  articles/control-center/user-management/images/user_management_enabled.png
  articles/control-center/user-management/images/user_management_user_selected.png
  articles/control-center/user-management/index.adoc
Labels: Language checked, control-center

#3683 refactor: rename examples to use validation suffix
  articles/components/combo-box/index.adoc
  articles/components/date-picker/index.adoc
  articles/components/date-time-picker/index.adoc
  articles/components/email-field/index.adoc
  articles/components/number-field/index.adoc
  articles/components/password-field/index.adoc
  articles/components/text-area/index.adoc
  articles/components/text-field/index.adoc
  articles/components/time-picker/index.adoc
  frontend/demo/component/combobox/combo-box-validation.ts
  frontend/demo/component/combobox/react/combo-box-validation.tsx
  frontend/demo/component/datepicker/date-picker-validation.ts
  frontend/demo/component/datepicker/react/date-picker-validation.tsx
  frontend/demo/component/datetimepicker/date-time-picker-validation.ts
  frontend/demo/component/datetimepicker/react/date-time-picker-validation.tsx
  frontend/demo/component/emailfield/email-field-validation.ts
  frontend/demo/component/emailfield/react/email-field-validation.tsx
  frontend/demo/component/numberfield/number-field-validation.ts
  frontend/demo/component/numberfield/react/number-field-validation.tsx
  frontend/demo/component/passwordfield/password-field-validation.ts
  frontend/demo/component/passwordfield/react/password-field-validation.tsx
  frontend/demo/component/textarea/react/text-area-validation.tsx
  frontend/demo/component/textarea/text-area-validation.ts
  frontend/demo/component/textfield/react/text-field-validation.tsx
  frontend/demo/component/textfield/text-field-validation.ts
  frontend/demo/component/timepicker/react/time-picker-validation.tsx
  frontend/demo/component/timepicker/time-picker-validation.ts
  src/main/java/com/vaadin/demo/component/combobox/ComboBoxValidation.java
  src/main/java/com/vaadin/demo/component/datepicker/DatePickerValidation.java
  src/main/java/com/vaadin/demo/component/datetimepicker/DateTimePickerValidation.java
  src/main/java/com/vaadin/demo/component/emailfield/EmailFieldValidation.java
  src/main/java/com/vaadin/demo/component/numberfield/NumberFieldValidation.java
  src/main/java/com/vaadin/demo/component/passwordfield/PasswordFieldValidation.java
  src/main/java/com/vaadin/demo/component/textarea/TextAreaValidation.java
  src/main/java/com/vaadin/demo/component/textfield/TextFieldValidation.java
  src/main/java/com/vaadin/demo/component/timepicker/TimePickerValidation.java
Labels: Language unchecked

#3688 add `ui-test-generation` panel to the copilot documentation
  articles/tools/copilot/index.adoc
Labels: Language unchecked

#3682 chore: document another option to always open browser
  articles/flow/integrations/spring/configuration.adoc
Labels: flow, Language unchecked

#3660 Persistence
  .github/styles/Vaadin/Abbr.yml
  .github/styles/config/vocabularies/Docs/accept.txt
  articles/building-apps/application-layer/index.adoc
  articles/building-apps/application-layer/persistence/flyway.adoc
  articles/building-apps/application-layer/persistence/index.adoc
  articles/building-apps/application-layer/persistence/repositories/index.adoc
  articles/building-apps/application-layer/persistence/repositories/jooq.adoc
  articles/building-apps/application-layer/persistence/repositories/jpa.adoc
  articles/building-apps/application-layer/persistence/repositories/pluggable.adoc
Labels: Language unchecked, the vaadin way

#3718 fix: fix outdated information on Hilla Gradle article
  articles/hilla/lit/reference/gradle.adoc
Labels: hilla

#3736 docs: use self-closing tags in inline React examples
  articles/hilla/guides/routing.adoc
  articles/hilla/lit/guides/forms/binder-load.adoc
  articles/hilla/lit/guides/forms/binder-validation.adoc
  articles/hilla/lit/guides/forms/binder.adoc
  articles/hilla/lit/guides/forms/binding-arrays.adoc
  articles/hilla/lit/guides/forms/vaadin-components.adoc
  articles/hilla/lit/start/basics/index.adoc
Labels: Language unchecked

#3737 docs: update outdated Hilla SSO kit npm package name
  articles/tools/sso/getting-started/hilla.adoc
Labels: Language unchecked

#3738 docs: use single quote in inline React examples
  articles/flow/integrations/hilla.adoc
  articles/flow/integrations/react.adoc
  articles/getting-started/tutorial/hilla/first-view.adoc
  articles/getting-started/tutorial/hilla/layout.adoc
  articles/getting-started/tutorial/hilla/reconnects.adoc
  articles/getting-started/tutorial/hilla/second-view.adoc
  articles/getting-started/views/index.adoc
  articles/hilla/guides/flow-integration.adoc
  articles/hilla/guides/routing.adoc
  articles/hilla/guides/testing.adoc
  articles/hilla/lit/guides/forms/binder-validation.adoc
  articles/hilla/lit/guides/forms/binding-arrays.adoc
  articles/hilla/lit/guides/forms/form-images.adoc
  articles/hilla/lit/guides/forms/reference.adoc
  articles/hilla/lit/guides/forms/vaadin-components.adoc
  articles/hilla/lit/guides/reactive-endpoints.adoc
  articles/hilla/lit/guides/upgrading/index.adoc
  articles/hilla/lit/start/basics/index.adoc
  articles/hilla/tutorial/index.adoc
Labels: Language unchecked

#3739 docs: fix indentation and some errors in inline TS examples
  articles/flow/integrations/react.adoc
  articles/getting-started/views/index.adoc
  articles/hilla/lit/guides/forms/binder-load.adoc
  articles/hilla/lit/guides/forms/binder-validation.adoc
  articles/hilla/lit/guides/forms/form-images.adoc
  articles/hilla/lit/guides/forms/form-status-tracking.adoc
  articles/hilla/lit/guides/forms/reference.adoc
  articles/hilla/lit/guides/forms/vaadin-components.adoc
  articles/hilla/lit/guides/reactive-endpoints.adoc
  articles/styling/index.adoc
Labels: Language unchecked

#3740 docs: remove mention of no longer existing setLabelAsHtml()
  articles/flow/security/advanced-topics/vulnerabilities.adoc
Labels: Language checking

#3747 Vulnerabilities Document - PR 3740
  articles/flow/security/advanced-topics/vulnerabilities.adoc
Labels: Language checked
