Repository vaadin/docs, pull requests merged in 2024-04, with the labels that each got.

#3319 fix: fix interface name in navigation docs (CP: latest)
  articles/routing/navigation.asciidoc
Labels: flow

#3289 docs: Kubernetes Kit serialization and deserialization callbacks
  articles/tools/kubernetes/session-replication.adoc
Labels: Language checked

#3345 Add a "Get Started" section for Copilot
  articles/tools/copilot/index.adoc
Labels: Language unchecked

#3369 docs: add CheckboxGroup read-only state examples
  articles/components/checkbox/index.adoc
  frontend/demo/component/checkbox/checkbox-readonly.ts
  frontend/demo/component/checkbox/react/checkbox-readonly.tsx
  src/main/java/com/vaadin/demo/component/checkbox/CheckboxReadonly.java
Labels: Language unchecked

#3370 docs: add docs for Checkbox required and helper features
  articles/components/checkbox/index.adoc
  frontend/demo/component/checkbox/checkbox-group-basic-features.ts
  frontend/demo/component/checkbox/checkbox-required.ts
  frontend/demo/component/checkbox/react/checkbox-group-basic-features.tsx
  frontend/demo/component/checkbox/react/checkbox-required.tsx
  src/main/java/com/vaadin/demo/component/checkbox/CheckboxGroupBasicFeatures.java
  src/main/java/com/vaadin/demo/component/checkbox/CheckboxRequired.java
Labels: Language unchecked

#3375 docs: add code example for SideNavItem target property
  articles/components/side-nav/index.adoc
Labels: Language unchecked

#3371 docs: add examples for GridPro cell editability
  articles/components/grid-pro/index.adoc
  frontend/demo/component/gridpro/grid-pro-cell-editability.ts
  frontend/demo/component/gridpro/react/grid-pro-cell-editability.tsx
  src/main/java/com/vaadin/demo/component/gridpro/GridProCellEditability.java
Labels: Language unchecked

#3378 docs: add documentation for treegrid scrollToIndex
  articles/components/tree-grid/index.adoc
  frontend/demo/component/tree-grid/react/tree-grid-scroll-to-index.tsx
  frontend/demo/component/tree-grid/tree-grid-scroll-to-index.ts
  src/main/java/com/vaadin/demo/component/treegrid/TreeGridScrollToIndex.java
Labels: Language unchecked

#3347 feat: add guide article for upgrading to 24.4
  articles/hilla/lit/guides/upgrading/index.adoc
Labels: hilla, Language checked, 24.4 beta

#3402 docs: add documentation for side-nav router integration
  articles/components/side-nav/index.adoc
  frontend/demo/component/side-nav/react/side-nav-router.tsx
Labels: Language unchecked

#3362 Minimum viable getting started
  articles/flow/_images/completed-app.gif
  articles/flow/quick-start.adoc
  articles/getting-started/views/index.adoc
  articles/hilla/quick-start.adoc
Labels: Language checked, 24.4 beta

#3241 Unified tutorial
  articles/flow/tutorial/index.adoc
  articles/getting-started/tutorial/deployment.adoc
  articles/getting-started/tutorial/flow/first-view.adoc
  articles/getting-started/tutorial/flow/images/author-highlighted.png
  articles/getting-started/tutorial/flow/images/channel-component.png
  articles/getting-started/tutorial/flow/images/channel-view.png
  articles/getting-started/tutorial/flow/images/color-avatars.png
  articles/getting-started/tutorial/flow/images/layout.png
  articles/getting-started/tutorial/flow/images/lobby-view.png
  articles/getting-started/tutorial/flow/images/styled-channel-view.png
  articles/getting-started/tutorial/flow/images/styled-lobby-view.png
  articles/getting-started/tutorial/flow/images/unstyled-channel-view.png
  articles/getting-started/tutorial/flow/images/unstyled-lobby-view.png
  articles/getting-started/tutorial/flow/index.adoc
  articles/getting-started/tutorial/flow/layout.adoc
  articles/getting-started/tutorial/flow/message-history.adoc
  articles/getting-started/tutorial/flow/second-view.adoc
  articles/getting-started/tutorial/flow/security.adoc
  articles/getting-started/tutorial/flow/styling.adoc
  articles/getting-started/tutorial/flow/ux-tweaks.adoc
  articles/getting-started/tutorial/hilla/first-view.adoc
  articles/getting-started/tutorial/hilla/images/channel-with-layout.png
  articles/getting-started/tutorial/hilla/images/channel_view_with_messages.png
  articles/getting-started/tutorial/hilla/images/channel_view_with_styles.png
  articles/getting-started/tutorial/hilla/images/channel_view_without_styles.png
  articles/getting-started/tutorial/hilla/images/chrome-offline.png
  articles/getting-started/tutorial/hilla/images/empty-layout.png
  articles/getting-started/tutorial/hilla/images/lobby-with-layout.png
  articles/getting-started/tutorial/hilla/images/lobby_view_with_channels.png.png
  articles/getting-started/tutorial/hilla/images/lobby_view_with_styles.png
  articles/getting-started/tutorial/hilla/images/lobby_view_without_styles.png
  articles/getting-started/tutorial/hilla/index.adoc
  articles/getting-started/tutorial/hilla/layout.adoc
  articles/getting-started/tutorial/hilla/message-history.adoc
  articles/getting-started/tutorial/hilla/reconnects.adoc
  articles/getting-started/tutorial/hilla/second-view.adoc
  articles/getting-started/tutorial/images/applayout-side.png
  articles/getting-started/tutorial/images/applayout-top.png
  articles/getting-started/tutorial/images/component-diagram.png
  articles/getting-started/tutorial/images/container-diagram.png
  articles/getting-started/tutorial/images/hilla_and_flow_uis.png
  articles/getting-started/tutorial/images/project-setup.png
  articles/getting-started/tutorial/index.adoc
  articles/getting-started/tutorial/next-steps.adoc
  articles/getting-started/tutorial/production-build.adoc
  articles/getting-started/tutorial/project-setup.adoc
  articles/hilla/tutorial/index.adoc
Labels: Language checking, 24.4 beta
