Repository vaadin/docs, pull requests merged in 2024-12, with the labels that each got.

#3967 Added thumbnail, version and description tag to popover
  articles/components/index.adoc
  articles/components/popover/index.adoc
  articles/components/popover/popover.png
Labels: Language unchecked

#3916 chore: document hotswap plugin watched-packages setting
  articles/flow/configuration/live-reload/hotswap-agent.adoc
Labels: flow, Language checked

#3953 docs: Start update
  articles/tools/start/_images/download-dialog.png
  articles/tools/start/_images/edit-entity.png
  articles/tools/start/_images/example-project.png
  articles/tools/start/_images/hello-world-starters.png
  articles/tools/start/_images/master-detail-template.png
  articles/tools/start/_images/my-projects.png
  articles/tools/start/_images/project-view.png
  articles/tools/start/_images/security-setup.png
  articles/tools/start/index.adoc
  articles/tools/start/view-builder/images/view-builder-delete-button.png
  articles/tools/start/view-builder/images/view-builder-layouts.png
  articles/tools/start/view-builder/images/view-builder-publish-gh.png
  articles/tools/start/view-builder/images/view-builder-share.png
  articles/tools/start/view-builder/images/view-builder-start.png
  articles/tools/start/view-builder/images/view-with-components.png
  articles/tools/start/view-builder/index.adoc
Labels: Language checked

#3971 Document TouchKit not working with MPR
  articles/tools/mpr/configuration/limitations.adoc
Labels: Language checked

#3949 docs: upload folder drag and drop
  articles/components/upload/index.adoc
Labels: Language checked

#3973 docs: context menu disable on click
  articles/components/context-menu/index.adoc
  src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuDisableOnClick.java
Labels: Language checked

#3870 docs: Adding more details about the copilot wrap with... feature.
  articles/tools/copilot/index.adoc
Labels: Language checked

#3978 Vaadin Way docs: Designing for responsiveness
  articles/building-apps/presentation-layer/design/images/color-contrast-chrome.png
  articles/building-apps/presentation-layer/design/images/color-contrast.png
  articles/building-apps/presentation-layer/design/images/color-palette.png
  articles/building-apps/presentation-layer/design/images/color-shapes1.png
  articles/building-apps/presentation-layer/design/images/color-shapes2.png
  articles/building-apps/presentation-layer/design/images/color-ui-example.png
  articles/building-apps/presentation-layer/design/images/responsiveness-browser-size.png
  articles/building-apps/presentation-layer/design/images/responsiveness-date-picker.png
  articles/building-apps/presentation-layer/design/images/responsiveness-native-inputs.png
  articles/building-apps/presentation-layer/design/images/responsiveness1.png
  articles/building-apps/presentation-layer/design/images/responsiveness2.png
  articles/building-apps/presentation-layer/design/images/responsiveness3.png
  articles/building-apps/presentation-layer/design/images/responsiveness4.png
  articles/building-apps/presentation-layer/design/images/sizing.png
  articles/building-apps/presentation-layer/design/images/spacing.png
  articles/building-apps/presentation-layer/design/images/typography-font-size.png
  articles/building-apps/presentation-layer/design/images/typography-monospace-css.png
  articles/building-apps/presentation-layer/design/images/typography-monospace.png
  articles/building-apps/presentation-layer/design/images/typography-serif-sans-serif.png
  articles/building-apps/presentation-layer/design/images/typography-type-scale.png
  articles/building-apps/presentation-layer/design/responsiveness.adoc
  articles/building-apps/presentation-layer/design/visuals/color.adoc
  articles/building-apps/presentation-layer/design/visuals/size-space.adoc
  articles/building-apps/presentation-layer/design/visuals/typography.adoc
Labels: Language unchecked, the vaadin way

#3970 docs: add section about wrapping to horizontal and vertical layouts
  articles/components/horizontal-layout/index.adoc
  articles/components/vertical-layout/index.adoc
  frontend/demo/component/basiclayouts/basic-layouts-horizontal-layout-wrapping.ts
  frontend/demo/component/basiclayouts/basic-layouts-vertical-layout-wrapping.ts
  frontend/demo/component/basiclayouts/react/basic-layouts-horizontal-layout-wrapping.tsx
  frontend/demo/component/basiclayouts/react/basic-layouts-vertical-layout-wrapping.tsx
  src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsHorizontalLayoutWrapping.java
  src/main/java/com/vaadin/demo/component/basiclayouts/BasicLayoutsVerticalLayoutWrapping.java
Labels: Language checked

#3924 Update Live reload configuration page to include Copilot
  articles/flow/configuration/live-reload/hotswap-agent.adoc
  articles/flow/configuration/live-reload/index.adoc
Labels: Language checked

#3994 Update analyzer-for-maven.adoc
  articles/tools/modernization-toolkit/analyzer-for-maven.adoc
Labels: Language unchecked

#4004 Replace old hilla.dev links
  README.md
  articles/flow/advanced/modifying-the-bootstrap-page.adoc
  articles/flow/configuration/pwa.adoc
  articles/flow/integrations/hilla.adoc
  articles/flow/security/enabling-security.adoc
  articles/hilla/lit/guides/reactive-endpoints.adoc
  articles/hilla/lit/guides/upgrading/index.adoc
  articles/hilla/lit/start/faq.adoc
Labels: hilla, Language unchecked

#4013 docs: add Dashboard documentation
  .github/styles/config/vocabularies/Docs/accept.txt
  articles/components/dashboard/dashboard.png
  articles/components/dashboard/index.adoc
  articles/components/dashboard/styling.adoc
  articles/components/index.adoc
  frontend/demo/component/dashboard/dashboard-announcements.ts
  frontend/demo/component/dashboard/dashboard-basic.ts
  frontend/demo/component/dashboard/dashboard-dense-layout.ts
  frontend/demo/component/dashboard/dashboard-editable.ts
  frontend/demo/component/dashboard/dashboard-internationalisation.ts
  frontend/demo/component/dashboard/dashboard-sections.ts
  frontend/demo/component/dashboard/dashboard-widget-contents.ts
  frontend/demo/component/dashboard/react/dashboard-announcements.tsx
  frontend/demo/component/dashboard/react/dashboard-basic.tsx
  frontend/demo/component/dashboard/react/dashboard-editable.tsx
  frontend/demo/component/dashboard/react/dashboard-internationalisation.tsx
  frontend/demo/component/dashboard/react/dashboard-sections.tsx
  frontend/demo/component/dashboard/react/dashboard-widget-contents.tsx
  frontend/demo/services/DashboardService.ts
  frontend/demo/services/mocks.ts
  frontend/themes/docs/dashboard.css
  frontend/themes/docs/styles.css
  src/main/java/com/vaadin/demo/component/dashboard/DashboardAnnouncements.java
  src/main/java/com/vaadin/demo/component/dashboard/DashboardBasic.java
  src/main/java/com/vaadin/demo/component/dashboard/DashboardEditable.java
  src/main/java/com/vaadin/demo/component/dashboard/DashboardInternationalisation.java
  src/main/java/com/vaadin/demo/component/dashboard/DashboardSections.java
  src/main/java/com/vaadin/demo/component/dashboard/DashboardService.java
  src/main/java/com/vaadin/demo/component/dashboard/DashboardStorage.java
  src/main/java/com/vaadin/demo/component/dashboard/DashboardWidgetContents.java
  src/main/java/com/vaadin/demo/component/dashboard/WidgetConfig.java
  src/main/resources/vaadin-featureflags.properties
Labels: Language unchecked

#4023 Added link to Forum thread for feedback
  articles/components/dashboard/index.adoc
Labels: Language unchecked

#3976 [Control Center] Remove references to the 1.0 installation process
  articles/control-center/getting-started/dependency-installation.adoc
  articles/control-center/getting-started/images/hostname-step.png
  articles/control-center/getting-started/images/install-step.png
  articles/control-center/getting-started/images/user-step.png
  articles/control-center/getting-started/images/welcome-step.png
  articles/control-center/security/index.adoc
Labels: Language unchecked

#4029 Fix tags
  articles/building-apps/spring-boot.adoc
  articles/components/basic-layouts/index.adoc
  articles/components/icons/index.adoc
  articles/flow/integrations/hilla.adoc
  articles/flow/integrations/spring/spring-boot.adoc
  articles/flow/production/cloud-providers/heroku/index.adoc
  articles/hilla/guides/security/index.adoc
  articles/hilla/index.adoc
  articles/tools/collaboration/components/index.adoc
  articles/tools/start/index.adoc
Labels: Language unchecked

#4042 feat: add skipLayouts description to the routing.adoc
  articles/hilla/guides/routing.adoc
Labels: hilla, Language unchecked

#4044 feat: add missing Subscription API descriptions
  articles/hilla/lit/guides/reactive-endpoints.adoc
Labels: hilla, Language unchecked

#3997 fix signal DX test issues
  articles/hilla/guides/full-stack-signals.adoc
Labels: hilla, Language checked
