Repository vaadin/docs, pull requests merged in 2024-06, with the labels that each got.

#3465 Describe what Flow is
  articles/flow/what-is-flow.adoc
Labels: Language unchecked

#3475 Make configuration of addChannelButton more explicit
  articles/getting-started/tutorial/flow/second-view.adoc
Labels: Language unchecked

#3472 Update Hilla docs for 24.4 authentication changes
  articles/hilla/lit/guides/upgrading/index.adoc
  frontend/demo/auth/LoginView.tsx
  frontend/demo/fusion/authentication/auth.ts
  frontend/demo/fusion/authentication/login-view.ts
Labels: hilla, Language unchecked

#3440 docs: document JAR package filtering
  articles/flow/integrations/spring/configuration.adoc
Labels: Language checked

#3499 fix: excluding hilla for a gradle project
  articles/upgrading/index.adoc
Labels: Language checked
