Repository vaadin/docs, pull requests merged in 2024-01, with the labels that each got.

#3041 feat: [autogrid/autoform] add section about autogrid filter options a…
  articles/react/components/auto-grid/index.adoc
Labels: Language checked

#3104 Adds devmode.hostsAllowed property
  articles/configuration/development-mode/dev-tools/index.adoc
  articles/configuration/properties.adoc
Labels: Language checked

#3115 cp: Adds devmode.hostsAllowed property (#3104)
  articles/flow/configuration/development-mode/dev-tools/index.adoc
  articles/flow/configuration/properties.adoc
Labels: Language checked

#3095 docs: add instructions to disable component tracker
  articles/configuration/development-mode/dev-tools/component-locator.adoc
  articles/configuration/properties.adoc
Labels: flow, Language checked

#3101 Add navigation examples for hybrid apps
  articles/integrations/hilla.adoc
Labels: Language checked

#3089 docs: update data-provider article for item index provider
  articles/binding-data/data-provider.adoc
Labels: flow, Language checked

#3119 docs: add instructions to disable component tracker (#3095) (CP: next)
  articles/flow/configuration/development-mode/dev-tools/component-locator.adoc
  articles/flow/configuration/properties.adoc
Labels: Language checked

#3128 fix: fix connect client prefix property name
  articles/lit/guides/client-middleware.adoc
Labels: hilla, Language unchecked

#3111 docs: add note about AllowInert on RPC calls
  articles/create-ui/element-api/client-server-rpc.asciidoc
Labels: flow, Language unchecked, Language checked

#3147 docs: add note about AllowInert on RPC calls (#3111) (CP: next)
  articles/flow/create-ui/element-api/client-server-rpc.adoc
Labels: Language checked

#3146 Describe session serialization timeout property in Kubernetes Kit
  articles/flow/tools/kubernetes/session-replication-debug-tool.adoc
Labels: Language checked

#2933 Make TS example consistent with Java code
  articles/lit/guides/security/spring-login.adoc
  frontend/demo/auth/authRoles.ts
  src/main/java/com/vaadin/demo/fusion/security/authentication/UserInfo.java
Labels: Language checked
