Repository vaadin/docs, pull requests merged in 2024-02, with the labels that each got.

#3153 Type Conversion - PR 2693 (next)
  articles/hilla/lit/reference/type-conversion.adoc
Labels: Language checked

#3155 Add reference.adoc - PR 2733
  articles/hilla/lit/guides/forms/reference.adoc
Labels: Language checked

#3156 Note on Microservice Architecture - PR 2962
  articles/hilla/lit/start/faq.adoc
Labels: Language checked

#3157 MultiSelectComboBox Examples - PR 2963
  articles/components/multi-select-combo-box/index.adoc
Labels: Language checked

#3159 Implementing Custom Svc for Auto Grid - PR 3008
  articles/components/auto-crud/index.adoc
  articles/components/auto-form/index.adoc
  articles/components/auto-grid/index.adoc
Labels: Language checked

#3160 Disable Sort & Filter Auto Grid - PR 3023
  articles/components/auto-grid/index.adoc
Labels: Language checked

#3168 Remove the 'Known Problems in Configuration' paragraph
  articles/flow/contributing/editor-settings.adoc
Labels: flow

#3175 chore: advise importing icon collections client-side
  articles/components/icons/index.adoc
Labels: Language unchecked

#3172 chore: fix typo on Embedding doc
  articles/flow/integrations/embedding/properties.adoc
Labels: Language unchecked

#3191 docs: update references to allowed and blocked packages
  articles/flow/guide/start/gradle.adoc
  articles/flow/integrations/spring/configuration.adoc
Labels: flow

#3188 docs: document menu-bar reverse-collapse
  articles/components/menu-bar/index.adoc
Labels: Language unchecked

#3178 chore: replace `@vaadin/hilla-core` with `@vaadin/hilla-frontend`
  articles/hilla/lit/guides/client-middleware.adoc
  articles/hilla/lit/guides/reactive-endpoints.adoc
  articles/hilla/lit/reference/connection-indicator.adoc
  articles/hilla/lit/reference/typescript-client.adoc
  articles/hilla/lit/start/basics/index.adoc
  frontend/demo/fusion/authentication/auth.ts
  frontend/demo/fusion/authentication/handle-session-expiration/connect-client.ts
  frontend/demo/fusion/authentication/handle-session-expiration/login-overlay.ts
  frontend/demo/fusion/authentication/login-view.ts
  frontend/demo/fusion/errorhandling/catch-error.ts
  frontend/demo/fusion/errorhandling/catch-invalid-args.ts
  frontend/demo/fusion/reactive/reactive-view.ts
  frontend/demo/pwa/offline/ts-view-with-endpoint.ts
  package-lock.json
  package.json
  pom.xml
Labels: hilla

#3207 fix: fix interface name in navigation docs
  articles/flow/routing/navigation.adoc
Labels: flow

#3196 fix: Add a note about public CTOR in WebComponentExporter
  articles/flow/integrations/embedding/clipboard.txt
  articles/flow/integrations/embedding/exporter.adoc
Labels: Language checked

#3220 chore: Fix the package for Constants
  articles/flow/configuration/properties.adoc
Labels: Language unchecked
