Repository vaadin/docs, pull requests merged in 2024-05, with the labels that each got.

#3409 fix diff highlighting in Hilla upgrade guide
  articles/hilla/lit/guides/upgrading/index.adoc
Labels: hilla

#3288 docs: Hilla file-based router usage
  articles/hilla/guides/data-grids/index.adoc
  articles/hilla/guides/routing.adoc
  articles/hilla/lit/guides/upgrading/index.adoc
  articles/hilla/reference/react-router.adoc
Labels: 24.4 beta

#3389 docs: add section about SideNav query parameters support
  articles/components/side-nav/index.adoc
Labels: Language checking

#3399 docs: extract file handling sections into separate tab
  articles/components/upload/file-handling.adoc
  articles/components/upload/flow.adoc
  articles/components/upload/index.adoc
Labels: Language checked

#3301 content badges for Flow, Hilla, and React
  articles/components/auto-crud/index.adoc
  articles/components/auto-form/index.adoc
  articles/components/auto-grid/index.adoc
  articles/components/grid/inline-editing.adoc
  articles/components/index.adoc
  articles/components/map/index.adoc
  articles/components/spreadsheet/index.adoc
  articles/tools/collaboration/index.adoc
  articles/tools/copilot/index.adoc
  articles/tools/index.adoc
  articles/tools/mpr/index.adoc
  dspublisher/theme/global.css
Labels: 24.4 beta

#3443 CoPilot Getting Started - PR 3345 & 3302
  articles/tools/copilot/index.adoc
  articles/tools/observability/index.adoc
Labels: Language checked

#3456 Unified tutorial
  articles/getting-started/tutorial/hilla/first-view.adoc
  articles/getting-started/tutorial/index.adoc
  articles/getting-started/tutorial/project-setup.adoc
Labels: Language checking

#3464 Mention ViewConfig in related options reference
  articles/hilla/guides/routing.adoc
Labels: Language unchecked

#3458 Update Discord to Forum
  articles/tutorial/overview.adoc
Labels: Language unchecked

#3449 RouteScopeOwner - PR 3291
  articles/flow/integrations/cdi/contexts.adoc
Labels: Language checked

#3445 CheckBox Features & Examples - PR 3370 & 3369
  articles/components/checkbox/index.adoc
Labels: Language checked

#3446 GridPro & TreeGrid - PR 3371 & 3378
  articles/components/grid-pro/index.adoc
  articles/components/tree-grid/index.adoc
Labels: Language checked

#3448 chore: Sync title with other tools
  articles/tools/copilot/index.adoc
Labels: Language unchecked

#3398 docs: add Charts subpage for Lit usage
  articles/components/charts/usage-with-lit.adoc
  frontend/demo/component/charts/charts-area.ts
  frontend/demo/component/charts/charts-column.ts
  frontend/demo/component/charts/charts-pie.ts
  frontend/demo/component/charts/charts-polar.ts
Labels: Language checked

#3397 docs: add Charts subpage for React usage
  articles/components/charts/usage-with-react.adoc
  frontend/demo/component/charts/react/charts-area.tsx
  frontend/demo/component/charts/react/charts-column.tsx
  frontend/demo/component/charts/react/charts-pie.tsx
  frontend/demo/component/charts/react/charts-polar.tsx
Labels: Language checked
