Repository vaadin/docs, pull requests merged in 2025-04, with the labels that each got.

#4216 docs: mark Control center commercial authentication methods
  articles/control-center/identity-management/index.adoc
  articles/control-center/index.adoc
  dspublisher/theme/global.css
Labels: Language checked

#4196 docs: add Control Center Troubleshooting section
  articles/control-center/troubleshooting/images/check_certificates_status.png
  articles/control-center/troubleshooting/images/describe_node.png
  articles/control-center/troubleshooting/images/docker_image_not_found.png
  articles/control-center/troubleshooting/images/nslookup_vaadin.png
  articles/control-center/troubleshooting/index.adoc
Labels: Language checked

#4237 Skeleton structure updates
  articles/building-apps/security/add-login/flow.adoc
  articles/building-apps/security/add-login/hilla.adoc
  articles/building-apps/security/add-logout/hilla.adoc
  articles/building-apps/security/protect-services/flow.adoc
  articles/building-apps/security/protect-services/hilla.adoc
  articles/building-apps/security/protect-views/flow.adoc
  articles/building-apps/security/protect-views/hilla.adoc
  articles/building-apps/views/add-router-layout/hilla.adoc
  articles/building-apps/views/add-view/flow.adoc
  articles/building-apps/views/add-view/hilla.adoc
  articles/building-apps/views/add-view/index.adoc
  articles/building-apps/views/navigate/flow.adoc
  articles/building-apps/views/navigate/hilla.adoc
  articles/building-apps/views/pass-data/query-parameters/hilla.adoc
  articles/getting-started/walk-through.adoc
Labels: Language unchecked

#4155 docs: replace com.vaadin.hilla.Nonnull usages
  articles/hilla/lit/reference/type-nullability.adoc
  articles/hilla/lit/start/basics/index.adoc
  src/main/java/com/vaadin/demo/component/dashboard/DashboardService.java
  src/main/java/com/vaadin/demo/component/dashboard/WidgetConfig.java
  src/main/java/com/vaadin/demo/fusion/crud/ProductDtoCrudService.java
  src/main/java/com/vaadin/demo/fusion/crud/ProductDtoListService.java
  src/main/java/com/vaadin/demo/fusion/forms/dialogs/NewsletterEndpoint.java
  src/main/java/com/vaadin/demo/fusion/reactive/ReactiveEndpoint.java
Labels: hilla

#4235 docs: cross-reference long-running-tasks.adoc from progress-bar
  articles/components/progress-bar/index.adoc
Labels: Language checked
