Repository vaadin/docs, pull requests merged in 2025-03, with the labels that each got.

#4164 docs: fix typo in method name
  articles/components/select/index.adoc
  articles/styling/styling-components/styling-component-instances.adoc
Labels: Language unchecked

#4152 Replace all existing imports of `react-router-dom`
  articles/flow/integrations/hilla.adoc
  articles/getting-started/tutorial/hilla/first-view.adoc
  articles/getting-started/tutorial/hilla/layout.adoc
  articles/getting-started/tutorial/hilla/second-view.adoc
  articles/hilla/guides/from-java-to-react.adoc
  articles/hilla/guides/routing.adoc
  articles/hilla/lit/guides/security/spring-login.adoc
  articles/hilla/lit/guides/upgrading/index.adoc
  articles/upgrading/index.adoc
Labels: hilla, Language unchecked

#4158 docs: custom item data for context menu and menu bar
  articles/components/context-menu/index.adoc
  articles/components/menu-bar/index.adoc
  frontend/demo/component/contextmenu/context-menu-custom-item-data.ts
  frontend/demo/component/contextmenu/react/context-menu-custom-item-data.tsx
  frontend/demo/component/menubar/menu-bar-custom-item-data.ts
  frontend/demo/component/menubar/react/menu-bar-custom-item-data.tsx
  src/main/java/com/vaadin/demo/component/contextmenu/ContextMenuCustomItemData.java
  src/main/java/com/vaadin/demo/component/menubar/MenuBarCustomItemData.java
Labels: Language checked

#4170 docs: add note in RichTextEditor documentation about asRequired use
  articles/components/rich-text-editor/index.adoc
Labels: Language unchecked

#4179 docs: [Control Center] add description of environment variable management feature
  articles/control-center/application-deployment/index.adoc
Labels: Language unchecked

#4178 [Control Center] Improve the clarity of application deployment documentation
  articles/control-center/application-deployment/images/app-deploy.png
  articles/control-center/application-deployment/index.adoc
Labels: Language unchecked

#4187 Remove preview tag from Control Center
  articles/control-center/index.adoc
Labels: Language unchecked

#4189 Docs/card index page item
  articles/components/card/card.png
  articles/components/card/index.adoc
  articles/components/dashboard/index.adoc
  articles/components/index.adoc
Labels: Language unchecked

#4192 Update MTK Analyzer version to 2.0.17
  articles/tools/modernization-toolkit/analyzer-for-maven.adoc
Labels: Language unchecked

#4169 docs: add missing has-error-message attribute to styling tables
  articles/components/checkbox/styling.adoc
  articles/components/combo-box/styling.adoc
  articles/components/custom-field/styling.adoc
  articles/components/date-picker/styling.adoc
  articles/components/date-time-picker/styling.adoc
  articles/components/email-field/styling.adoc
  articles/components/multi-select-combo-box/styling.adoc
  articles/components/number-field/styling.adoc
  articles/components/password-field/styling.adoc
  articles/components/radio-button/styling.adoc
  articles/components/select/styling.adoc
  articles/components/text-area/styling.adoc
  articles/components/text-field/styling.adoc
  articles/components/time-picker/styling.adoc
  articles/styling/styling-components/sharing-styles.adoc
Labels: Language unchecked

#4210 Make the Getting Starter guide easier to navigate
  articles/getting-started/next-steps.adoc
  articles/getting-started/start/index.adoc
  articles/getting-started/walk-through.adoc
Labels: Language unchecked

#4213 chore: remove incorrect duplicate backticks
  articles/flow/integrations/embedding/index.adoc
  articles/flow/integrations/hilla.adoc
  articles/flow/production/cloud-providers/aws/index.adoc
  articles/flow/testing/playwright.adoc
  articles/upgrading/index.adoc
Labels: Language unchecked

#4211 Instructions for writing different types of Vaadin documentation
  articles/contributing/docs/types.adoc
Labels: Language unchecked

#4214 Updated suggested JRE version to 21
  articles/control-center/application-deployment/index.adoc
Labels: Language unchecked

#4173 docs: add frontendIgnoreVersionChecks plugin param
  articles/flow/configuration/maven.adoc
  articles/flow/configuration/properties.adoc
Labels: flow, Language checked

#4174 docs: add frontend.hotdeploy.dependencies documentation
  articles/flow/configuration/properties.adoc
Labels: flow, Language checked

#4176 docs: mention queueuing messages when no response
  articles/flow/advanced/server-client-communication.adoc
Labels: flow, Language checked

#4195 docs: document proper integration with Spring Security Concurrency
  articles/flow/security/enabling-security.adoc
Labels: flow, Language checked
