Repository vaadin/docs, pull requests merged in 2025-02, with the labels that each got.

#4091 chore: Add a note to clean-frontend about recently added properties
  articles/flow/configuration/properties.adoc
  articles/flow/production/production-build.adoc
Labels: Language checked

#4102 Update MTK Analyzer version to 2.0.14
  articles/tools/modernization-toolkit/analyzer-for-maven.adoc
Labels: Language unchecked

#4105 Update index.adoc
  articles/index.adoc
Labels: Language unchecked, documentation

#4103 feat: Card component
  articles/components/card/index.adoc
  articles/components/card/styling.adoc
  frontend/demo/component/card/card-combine-variants.ts
  frontend/demo/component/card/card-content.ts
  frontend/demo/component/card/card-cover-media.ts
  frontend/demo/component/card/card-elevated.ts
  frontend/demo/component/card/card-features.ts
  frontend/demo/component/card/card-footer.ts
  frontend/demo/component/card/card-header-prefix.ts
  frontend/demo/component/card/card-header-suffix.ts
  frontend/demo/component/card/card-header.ts
  frontend/demo/component/card/card-horizontal.ts
  frontend/demo/component/card/card-media.ts
  frontend/demo/component/card/card-outlined.ts
  frontend/demo/component/card/card-stretch-media.ts
  frontend/demo/component/card/card-subtitle.ts
  frontend/demo/component/card/card-title.ts
  frontend/demo/component/card/react/card-combine-variants.tsx
  frontend/demo/component/card/react/card-content.tsx
  frontend/demo/component/card/react/card-cover-media.tsx
  frontend/demo/component/card/react/card-elevated.tsx
  frontend/demo/component/card/react/card-footer.tsx
  frontend/demo/component/card/react/card-header-prefix.tsx
  frontend/demo/component/card/react/card-header-suffix.tsx
  frontend/demo/component/card/react/card-header.tsx
  frontend/demo/component/card/react/card-horizontal.tsx
  frontend/demo/component/card/react/card-media.tsx
  frontend/demo/component/card/react/card-outlined.tsx
  frontend/demo/component/card/react/card-stretch-media.tsx
  frontend/demo/component/card/react/card-subtitle.tsx
  frontend/demo/component/card/react/card-title.tsx
  frontend/types.d.ts
  src/main/resources/images/lapland.avif
  src/main/resources/vaadin-featureflags.properties
Labels: Language unchecked

#4107 Update MTK Analyzer version to 2.0.15
  articles/tools/modernization-toolkit/analyzer-for-maven.adoc
Labels: Language unchecked

#4082 docs: make Forms more prominent in documentation
  articles/flow/binding-data/components-binder.adoc
  articles/flow/binding-data/index.adoc
Labels: Language checked

#4095 [Control Center] Add instructions to upgrade from 1.1 and later
  .github/styles/config/vocabularies/Docs/accept.txt
  articles/control-center/getting-started/upgrade.adoc
Labels: Language checked

#4094 fix: Update parameters
  articles/flow/configuration/properties.adoc
Labels: Language checked

#4077 feat: explain how to make disabled buttons accessible
  articles/components/button/index.adoc
  articles/components/menu-bar/index.adoc
Labels: Language checking

#4117 Add guide for automatic DNS and certificate management in Control Center
  articles/control-center/getting-started/automatic-dns-and-cert.adoc
Labels: Language unchecked

#4101 feat(hilla): add a download example
  articles/hilla/guides/uploads-downloads.adoc
  frontend/demo/fusion/forms/upload/download.tsx
  src/main/java/com/vaadin/demo/SecurityConfig.java
  src/main/java/com/vaadin/demo/fusion/download/FileDownloadEndpoint.java
Labels: hilla, Language checked

#4118 Add unserializable component wrapper in Kubernetes Kit documentation
  .github/styles/config/vocabularies/Docs/accept.txt
  articles/tools/kubernetes/session-replication.adoc
Labels: Language checked

#4127 Add reference to UnserializableComponentWrapper
  articles/components/spreadsheet/index.adoc
Labels: Language checked

#4150 docs: ordered layouts custom spacing
  articles/components/horizontal-layout/index.adoc
  articles/components/vertical-layout/index.adoc
Labels: Language unchecked

#4128 docs: add slot based horizontal alignment examples
  articles/components/horizontal-layout/index.adoc
  frontend/demo/component/horizontal-layout/horizontal-layout-slots-wrapping.ts
  frontend/demo/component/horizontal-layout/horizontal-layout-slots.ts
  frontend/demo/component/horizontal-layout/react/horizontal-layout-slots-wrapping.tsx
  frontend/demo/component/horizontal-layout/react/horizontal-layout-slots.tsx
  src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutSlots.java
  src/main/java/com/vaadin/demo/component/horizontallayout/HorizontalLayoutSlotsWrapping.java
Labels: Language checking

#4160 Fix typo in Build Contact Form page title
  articles/tools/designer/getting-started/build-your-contact-form.adoc
Labels: Language unchecked

#4159 Add Vaadin Cookbook under Building Apps
  articles/building-apps/cookbook.adoc
Labels: Language unchecked, documentation
