Repository vaadin/docs, pull requests merged in 2025-08, with the labels that each got.

#4450 chore: add documentation for Vaadin Executor
  articles/flow/advanced/service-executor.adoc
  articles/flow/integrations/cdi/service-beans.adoc
  articles/flow/integrations/quarkus.adoc
  articles/flow/integrations/spring/configuration.adoc
Labels: flow

#4392 doc: Copilot new features update
  articles/tools/copilot/index.adoc
Labels: target/main

#4440 Add data retention and upgrade safety advice
  articles/control-center/getting-started/uninstall.adoc
  articles/control-center/getting-started/upgrade.adoc
Labels: target/main

#4445 Fix: Complete description for Upload documentation
  articles/components/upload/file-handling.adoc
  articles/components/upload/index.adoc
Labels: flow, target/main

#4435 Update feature-pack.adoc
  articles/tools/modernization-toolkit/feature-pack.adoc
Labels: target/main

#4525 Add link to Java language as it is with React and TS
  articles/getting-started/prerequisites.adoc
Labels: target/main

#4522 docs: Guide on creating Custom Field in flow
  articles/building-apps/forms-data/create-custom-field/index.adoc
Labels: flow, target/main

#4547 chore: update CDI article for Jakarta EE
  articles/flow/integrations/cdi/index.adoc
Labels: flow

#4561 chore: exclude observability kit from runtime
  pom.xml
Labels: target/v24
