Repository vaadin/docs, pull requests merged in 2025-01, with the labels that each got.

#4050 Update MTK Analyzer version to 2.0.11
  articles/tools/modernization-toolkit/analyzer-for-maven.adoc
Labels: Language unchecked

#4039 Add meta data guide for docs contributors
  articles/contributing/docs/index.adoc
Labels: Language checked

#4058 Extend documentation for customers that have not been assisted
  articles/tools/modernization-toolkit/dragonfly.adoc
Labels: Language unchecked

#4059 docs: add documentation for OAuth2 login
  articles/flow/integrations/spring/oauth2.adoc
Labels: Language checked

#4053 docs: Mark dev-tools deprecated in favour of Copilot
  articles/flow/configuration/development-mode/dev-tools/component-locator.adoc
  articles/flow/configuration/development-mode/dev-tools/dev-tools-plugin-support.adoc
  articles/flow/configuration/development-mode/dev-tools/index.adoc
  articles/flow/configuration/properties.adoc
Labels: Language checked

#4043 add instructions to upgrade Control Center from 1.0 to 1.1
  articles/control-center/getting-started/upgrade.adoc
Labels: Language checked

#4072 fix: fix Vaadin url mapping documentation
  articles/flow/integrations/spring/configuration.adoc
Labels: flow, Language checked

#4052 fix: clarify Operation return type
  articles/hilla/guides/full-stack-signals.adoc
Labels: hilla, Language checked

#4073 fix: Update layout document
  articles/components/app-layout/index.adoc
  articles/flow/routing/layout.adoc
Labels: Language checked

#4075 docs: lumo pointer focus ring
  articles/styling/lumo/lumo-style-properties/interaction.adoc
Labels: Language checked

#4086 MTK Analyzer 2.0.12 version update
  articles/tools/modernization-toolkit/analyzer-for-maven.adoc
Labels: Language unchecked

#4070 docs: add note about nav target path uniqueness
  articles/flow/routing/route.adoc
Labels: Language checked

#4089 [Control Center] Add uninstall instructions
  articles/control-center/getting-started/uninstall.adoc
Labels: Language checked
